### ISSUE TITLE
Discord Dice-Maiden bot, no longer working?

### ISSUE THREAD

**Issue by Keiracat1337** [Humblemonk/DiceMaiden#1]
She is no longer rolling. We have tried kicking her and bringing her back. Reloading Discord. And even multiple people rolling her !roll help. Nothing is happening. Any advice? She was the perfect bot for our online post stories.

**Comment by Humblemonk** [comment]
Hey, thanks for letting me know. There was a recent uptick of hundreds of servers utilizing the bot which most likely caused this issue. I will take a look and see whats up.

**Comment by Humblemonk** [comment]
Just upgraded the digital ocean droplet and it looks like a few of the gems required upgrading as well. Things look good now but I will leave this issue open for a few days and see how it pans out. 

Thanks again for letting me know! Update the issue if you are still seeing problems.

**Comment by Keiracat1337** [comment]
Thank you so much for getting back so soon!
 I was expecting the 3-5 business days.

**Comment by Arosea** [comment]
It's happening again I'm afraid, multiple servers are having issues where the dice maiden is appearing offline and refusing to roll

**Comment by Humblemonk** [comment]
Hey Arosea,

The bot should be back up now. The same issue as last time was a huge
influx of new servers utilizing the bot.

**Comment by tskye** [comment]
It's happening again on our group's discord server. Dice Maiden wasn't responding to !roll commands earlier, and is now offline.

**Comment by Humblemonk** [comment]
Yea looking into it now. Looks like discord reset my API due to abuse and may have ip banned the bot. Will update when its back online.

**Comment by DarkDot** [comment]
It's dead again

**Comment by Twitchell635** [comment]
I am having similar problems. the bot goes offline for a while but even when its on there is either no response or a huge delay when it does respond. Last time my group got her to roll it took 8 minutes to get a result back.
