### ISSUE TITLE
REQUEST: Increase dice pool and just display outcome and/or option to set a variable as an upper bound

### ISSUE THREAD

**Issue by reecer62** [Humblemonk/DiceMaiden#10]
Enjoying the bot so far!

Currently, the dice pool is limited to 500. It would be fantastic if there was an option to roll a dice pool where the upper bound is set as a variable/ from a command line argument. Also, the ability to skip displaying the individual rolls and just display the outcome.

**Comment by Humblemonk** [comment]
I am not going to support a dice pool greater than 500 but I can see the benefit of skipping individual rolls. Will look into it

**Comment by Humblemonk** [comment]
how this will most likely looks is as follows:
`!roll s 4d10`

Specifiying s before a role will simplify the output and not show each individual dice.  Also, to add some clarification as to why I will not add support for more than a dice pool of 500 is that it can easily cause the bot to hang.

**Comment by Humblemonk** [comment]
Simplify roll output option is being rolled out now.
