### ISSUE TITLE
Alias for Shadowrun

### ISSUE THREAD

**Issue by lavelain** [Humblemonk/DiceMaiden#101]
Hello! I was wondering if it'd be possible to add an alias for Shadowrun dice
You'd need to roll d6's only, a target value of 5 or higher and 1s would subtract from successes.
and maybe an option for dice to explode on 6s from the alias would be great if possible as well.

Thank you!

**Comment by Humblemonk** [comment]
Is there a specific edition where 1s would subtract from successes? I dont think thats how it works in shadowrun 5e

**Comment by lavelain** [comment]
It is that way in 3 and 4e for sure

On Aug 15, 2020, at 9:09 PM, Humblemonk <notifications@github.com> wrote:

﻿

Is there a specific edition where 1s would subtract from successes? I dont think thats how it works in shadowrun 5e

**Comment by ThatGuyWhatsMadeofCheese** [comment]
I could write this one, but I don't know what the alias tag should be.

**Comment by lavelain** [comment]
Hrm. Good point. SR won’t work as the rules vary according to edition and I imagine having numbers wouldn’t work either. Maybe SRF for fourth and SRV for fiVe?

On Aug 16, 2020, at 9:35 AM, ThatGuyWhatsMadeofCheese <notifications@github.com> wrote:

﻿

I could write this one, but I don't know what the alias tag should be.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Works for me, sure. But would you want it to be 
!roll 7srf
or
!roll srf7
?

Personally, I prefer having the variable at the end, so it's easier to change after you paste the command, but I admit it looks more 'right' at the beginning. And feels more right if you're typing the whole thing out.

**Comment by lavelain** [comment]
I agree, having at the front looks better, but I also agree that having the variable at the end makes it easier to change post-paste. Thank you for taking time to make this, I’ll defer to your preference

On Aug 16, 2020, at 5:06 PM, ThatGuyWhatsMadeofCheese <notifications@github.com> wrote:

﻿

Works for me, sure. But would you want it to be
!roll 7srf
or
!roll srf7
?

Personally, I prefer having the variable at the end, so it's easier to change after you paste the command, but I admit it looks more 'right' at the beginning. And feels more right if you're typing the whole thing out.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Np! I'm just trying to help out some, since Humblemonk was willing to add an alias for a game still in playtesting. I haven't gotten around to actually learning Ruby yet, but I can do some simple regex to make the aliases, at least :)

**Comment by Humblemonk** [comment]
Going to close this one out for now. Please reference my comment in the pull request.
