### ISSUE TITLE
Quick rolls for d20’s

### ISSUE THREAD

**Issue by ShadowGamer3** [Humblemonk/DiceMaiden#110]
Could you add quick rolls for d20’s?

Examples:

!roll attack (insert modifiers) - (!roll 1d20 + (modifiers) ! Attack Roll)

!roll skill (insert mod) - (!roll 1d20 + (modifiers) ! Skill Check)

!roll save (insert mod) - (!roll 1d20 + (modifiers) ! Saving Throw)

These would be much faster to type, especially on a mobile keyboard, and make sorting through the rolls during a Discord D&D / Pathfinder game much easier for Dungeon Masters, and it would make context for those rolls much easier to understand when performed.

**Comment by Humblemonk** [comment]
what would modifiers be in this scenario? Would they only be positive? Something like 1d20 + 20?
