### ISSUE TITLE
Feature Request: Sort the results of multiple sets

### ISSUE THREAD

**Issue by afgriffiths** [Humblemonk/DiceMaiden#112]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when, as a DM I need to roll initiative for a large group of monsters to determine the order of actions for my players and the monsters in combat e.g. `!roll 10 1d6 - 1` to roll initiative for a group of 10 monsters.

Having the results of the rolls sorted would help immensely in determining the order of actions for the monsters and players.

**Describe the solution you'd like**
Have an option such as `!sort` that will sort the results of multiple sets of dice rolls in either ascending or descending order.

**Describe alternatives you've considered**
Writing another discord bot that wraps around dice maiden and provides sort functionality

**Comment by Humblemonk** [comment]
Going to close this out as won't do as it would require a complete rewrite of the roll set functionality to support this.
