### ISSUE TITLE
How about a `!shame` feature?

### ISSUE THREAD

**Issue by thatandromeda** [Humblemonk/DiceMaiden#113]
**Is your feature request related to a problem? Please describe.**
Sometimes our dice roll badly, repeatedly, and we would like to shame them.

**Describe the solution you'd like**
A `!shame` command, analogous to `!roll`. DiceMaiden will respond by describing the dice-shaming steps she has taken.

**Describe alternatives you've considered**
Sadly shrugging when the party crit fails thrice in a row, because what can you do.

**Additional context**
I'm perfectly happy to write this feature and open a PR. I have ideas! I just want to know if this would be a welcome PR before I write it.

**Comment by Humblemonk** [comment]
Hah that's pretty great :) and a funny idea but I think ill pass on adding it for now. Need to keep working on the game aliases first!

**Comment by thatandromeda** [comment]
👍
