### ISSUE TITLE
Docker for Self-Hosting

### ISSUE THREAD

**Issue by oxr463** [Humblemonk/DiceMaiden#117]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

It would be nice to have an official Docker image to deploy for self-hosting.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Humblemonk** [comment]
I like this idea! Its currently pretty hard for folks to get a single instance setup right now without some linux + ruby experience. This might make things a little easier
