### ISSUE TITLE
Displayed "[name] Roll:" does not match current nickname.

### ISSUE THREAD

**Issue by lunarskye** [Humblemonk/DiceMaiden#119]
**Describe the bug**
Not outputting current user nickname with roll. Output is either default Discord username or one from some sort of cache. 

**To Reproduce**
1. Change Discord nickname
2. Execute !roll command
3. Observe displayed "[name] Roll:" does not match current nickname.

**Expected behavior**
Displayed name with roll will match current nickname set in Discord.

**Screenshots**
![dicemaiden_bug_nickname_output](https://user-images.githubusercontent.com/74117966/98451925-cba4e080-2107-11eb-84fd-86f8a8caf5d3.PNG)

![dicemaiden_bug_nickname_output2](https://user-images.githubusercontent.com/74117966/98451914-b465f300-2107-11eb-94a2-b6997d56db2f.PNG)

**Additional context**
Used to work flawlessly, noticed difference within the last couple weeks.

**Comment by Humblemonk** [comment]
This is an issue with discordrb. Once the library gets updated, ill pull the patch and this should be resolved.

**Comment by Humblemonk** [comment]
Fix for this issue is being deployed now!
