### ISSUE TITLE
REQUEST: Include Fudge/Fate Dice option

### ISSUE THREAD

**Issue by fabiocosta0305** [Humblemonk/DiceMaiden#12]
Please, include an option for rolls with Fudge/Fate Dice

**Comment by Humblemonk** [comment]
This should be pretty easy to do. I will look into it

**Comment by orffen** [comment]
The algorithm for this is (4d3 - 8).

Could we get an alias for this as something similar to `!roll 4f` which would translate to `!roll 4d3 -8`? Similarly we could have `!roll 6f` to get `6d3-8`.

**Comment by Humblemonk** [comment]
This functionality is now supported! It is documented under the "Alias" section of the readme. Going to close this issue out for now. Can always reopen if a bug crops up.
