### ISSUE TITLE
Private Rolls

### ISSUE THREAD

**Issue by DylanBanta** [Humblemonk/DiceMaiden#120]
**Is your feature request related to a problem? Please describe.**

Our group allows the DM to roll privately, or to show the roll only to 1 player.

**Describe the solution you'd like**

Add command !roll p
For only the user (DM) to see the roll
!roll p 1d6
//Send the roll as a message to the user (DM)

For user (DM) and one other player to see roll
!roll p 1d6 @player
//Send the roll as a message to the user (DM) and the tagged player

**Describe alternatives you've considered**
//TODO

**Additional context**
//TODO

**Comment by Humblemonk** [comment]
For sending a message to the DM, the best solution right now is to send a private message to the bot for private rolls. No plan to support direct message rolls from a channel.

**Comment by Humblemonk** [comment]
reopening this to have private responses to rolls within a channel
