### ISSUE TITLE
Narrative rolls

### ISSUE THREAD

**Issue by nocon** [Humblemonk/DiceMaiden#122]
**Is your feature request related to a problem? Please describe.**
I think that dice bots offer an unique storytelling opportunity that can't be achieved in any other way. Players trust them as if they're physical dice, but they're not in reality. Consider for a second what if narrator could affect the bot responses. In any adventure where the sanity of players is in question, subtle changes like slightly different characters or brackets would mess with them. The bot could go outright silent or respond with sequences like ```6 6 6``` (or ```cthulhu fhtagn```). Out of order roll results could be used as clues. I imagine you can think of more uses, and would love to hear about them. The shock could make that one session unforgettable. 

**Describe the solution you'd like**
It could be controlled in a similar fashion as other DM settings. A PM to the bot would affect the result of the next roll only.

Naturally, it could be abused, especially when a dishonest player manages the channel for the narrator. This could be mitigated by limiting the possible responses. Free inputs that look too much like ordinary rolls could be rejected (the implementation would be a fun challenge). Everyone on the channel could be allowed to PM the bot to learn the last time the feature was used.

**Comment by ShadowGamer3** [comment]
Great idea!  Could check for a DM role before allowing the feature to be used, and could warn the bot that it's gonna happen in a DM, then the next roll command looks normal, but was actually predetermined.

**Comment by daemionfox** [comment]
Would love to see this gor our current game!

**Comment by GMJoe** [comment]
This'd definitely need some checks and balances to prevent it from being a tool for cheating and abuse. (In fact, I'd prefer not to have it at all, but if the feature can be disabled, that's good enough for me.)

**Comment by Humblemonk** [comment]
Sorry going to close this out as a wont do. Have no interest in implementing this and it would be a pain now with the slash command implementation and requirements
