### ISSUE TITLE
Add ability for totals in roll sets

### ISSUE THREAD

**Issue by Sapper-Morton** [Humblemonk/DiceMaiden#124]
Usually people roll stats for a game like !roll 6 4d6k3 but some game systems require character to have atleast certain amount of points total. Currently DM doesn't shows totals for these rolls.

Maybe add another toggle which makes DM to count and show rolls at the end like this:
!roll 6t 4d6k3
Dice Maiden: Anonymous Coward Rolls:
[6, 3, 3, 2] Result: 12
[6, 3, 2, 1] Result: 11
[6, 5, 4, 2] Result: 15
[6, 5, 4, 1] Result: 15
[4, 4, 3, 1] Result: 11
[6, 5, 3, 2] Result: 14
Total: 78

**Comment by Humblemonk** [comment]
Not a bad idea! I think I will just add it as a default parameter. Thanks for the suggestion!
