### ISSUE TITLE
Alias to quickly roll a new DnD character

### ISSUE THREAD

**Issue by DollarStarNova** [Humblemonk/DiceMaiden#128]
**Is your feature request related to a problem? Please describe.**
Currently, I have to explain to people new to dice maiden to run "!roll 6 4d6 k3" to roll up their character. this isn't awful but I feel this is a common enough use of the system that it should have an alias.

**Describe the solution you'd like**

Typing "!roll dndstats" or similar would return !roll 6 4d6 k3 with each roll also labelled with the modifier it gives (e.g. +2 for 14, +0 for 10 etc.)

**Describe alternatives you've considered**
There is no current way to also return the modifier that I know of. Allowing us to create custom roll functions may be a way to do this but it would be longer than just adding a dedicated command.

**Additional context**
DnD is a very popular system, so I think this is a feature many people will find useful.

**Comment by GMJoe** [comment]
Older editions of D&D required a player to roll 3d6 for each stat instead of 4d6-and-drop-the-lowest, so it'd be good to have support for that, too.

Oh, and the ability to supress modifiers would also be useful, as different editions of D&D calculate modifiers differently, sometimes on a per-stat basis.

**Comment by Humblemonk** [comment]
Before I close this out, which editions of DnD support the "!roll 6 4d6 k3"? I would want to document that in the readme file

**Comment by Lank891** [comment]
Afaik 6 4d6 drop lowest is preferred in dnd 4e, 5e and pathfinder 1e

**Comment by Lank891** [comment]
Apparently other sources tells that it is not preferred in 4e but it is in 3.5e huh, but for sure it is preferred for 5e and it is "Standard" method for pathfinder 1e

**Comment by GMJoe** [comment]
AD&D Second Edition used "3d6 for each stat" as its standard method, but also suggested "4d6-and-drop-the-lowest" as one of several alternative stat generation methods.

**Comment by Humblemonk** [comment]
Perfect, thanks folks!
