### ISSUE TITLE
User ID Shown In Chat

### ISSUE THREAD

**Issue by 1ordsudo** [Humblemonk/DiceMaiden#131]
**Describe the bug**
!roll d2 !@username

**To Reproduce**
1. Type in the following syntax !roll d2!@username 
2. Hit enter
3. The 18 character string will be shown in the chat 

**Expected behavior**
No return or output of user character string data.

**Comment by Humblemonk** [comment]
Thanks for sending in the bug report. This was working in the past but it looks like it broke with the recent discordrb update. I should have an update pushed out tonight that strips user mentions from comments again.  Allow the bot to do mentions can become a bit spammy on some servers and super annoying
