### ISSUE TITLE
REQUEST: Ability to bulk roll with modifiers

### ISSUE THREAD

**Issue by diztracshon** [Humblemonk/DiceMaiden#133]
**Is your feature request related to a problem? Please describe.**
Whenever I try to add a modifier to a bulk roll, eg: "!roll 6 4d6k3" I get the message "Error: Extra numbers detected!", and I would like for this feature to work with any kind of roll, so that I could, for example, bulk roll stats in dnd or something.

**Describe the solution you'd like**
I would like for something like "!roll 6 4d6 k3" to roll 4d6 drop one 6 times, Maybe a new modifier like b for batch, so it might be "!roll 4d6 k3 b6"?

**Describe alternatives you've considered**
An alternative feature could be a !repeat that rolls whatever was last rolled again. Or obviously you can just copy and past the command.

**Additional context**
Bulk rolling something like stats in the method I mentioned above is quite common in ttrpgs and doesn't appear to be possible with dice maiden unless I'm stupid or something.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Note: it only seems to throw this error if there's a custom prefix on the server, and you're using !roll instead of the custom prefix.

**Comment by diztracshon** [comment]
Oh, thanks, I'll close this then

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Well, it is still a bug, it's just more of an edge case.

**Comment by diztracshon** [comment]
Will I make a bug report then? Seems more organised than leaving the feature request
