### ISSUE TITLE
BUG: Bulk roll error when custom prefix not used

### ISSUE THREAD

**Issue by diztracshon** [Humblemonk/DiceMaiden#134]
**Describe the bug**
When attempting a bulk roll with the k modifier using the default syntax (that is: "!roll 6 4d6 k3") when there is a custom prefix set (in this case: "!r") Dice Maiden responds with "Error: Extra numbers detected!"

**To Reproduce**
1. Set the prefix with "!dm prefix r"
2. Type "!roll 6 4d6 k3"
3. Dice Maiden returns the error

**Expected behavior**
Expected behaviour is Dice Maiden outputting a set of 6 rolls of 4d6 dropping the lowest dice, eg:
"User Rolls:
[6, 3, 3, 1] Result: 12
[5, 4, 3, 2] Result: 12
[3, 1, 1, 1] Result: 5
[6, 5, 2, 1] Result: 13
[6, 5, 3, 1] Result: 14
[6, 3, 2, 1] Result: 11"

**Screenshots**
![bulk roll](https://user-images.githubusercontent.com/48117348/103852415-edb6e100-50ff-11eb-8832-01f941d68b42.jpg)

**Additional context**
This appears to only happen when a custom prefix is set.

**Comment by Humblemonk** [comment]
Thanks for the report. I am noticing that the bot is ignoring the custom prefix right now for other rolls as well. Going to look into this asap

**Comment by Humblemonk** [comment]
A fix for this is being deployed now

**Comment by diztracshon** [comment]
Cool, the fix is working for me, will I close the report?

**Comment by Humblemonk** [comment]
I got it. Thanks again for the submission!

**Comment by diztracshon** [comment]
No prob, thanks for the bot, best I've used so far
