### ISSUE TITLE
Custom prefix bug

### ISSUE THREAD

**Issue by Trendinghobbit** [Humblemonk/DiceMaiden#135]
**Describe the bug**
Changing the prefix of the bot makes it not respond to any commands.

**To Reproduce**
1. Invite the bot into a server
2. Use the "!dm prefix" command and change the prefix
3. Attempt to use any other command with the new prefix

**Expected behavior**
I expected the bot to normally respond to commands with the new prefix.

**Screenshots**
I think screenshots wouldn't add any meaningful context here.

**Additional context**
I believe one of the new updates might have caused this. The bot was working just fine about 3 days ago.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Could not reproduce; it's working as expected for me

![image](https://user-images.githubusercontent.com/69303484/104086518-50060380-521e-11eb-9c1a-efc9228c2b23.png)

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Oh, no, wait. I'm guessing before this update, you could type, for example, {!r1d2} without a space between the prefix and the die roll, which you can't do anymore because now it checks for whitespace after the prefix.

**Comment by Trendinghobbit** [comment]
That must be it then. I remember setting the prefix to "!" so it'd be !!1d20 for example. I didn't find anything online so i assumed it was a bug. Thanks for your help ^^
