### ISSUE TITLE
FEATURE REQUEST: Add a Help Command

### ISSUE THREAD

**Issue by Naequarwe** [Humblemonk/DiceMaiden#138]
**Is your feature request related to a problem? Please describe.**
i found it hard to understand how to use the bot until i went to the bot page, my internet and web-page takes forever to open and i want to know the commands quicker.

**Describe the solution you'd like**
what i would like to see happen is a help command be added allowing for better use of the bot in the server

**Describe alternatives you've considered**
if you don't want to make a help command then you could make a command that makes a link to the bot webpage

**Additional context**
i have no additional context, i just hope you understand how much easier it would be to use your bot if you had a help command.

**Comment by Humblemonk** [comment]
Hey! So there is a limited help command by running `!roll help` output below:
```Synopsis:
    !roll xdx [OPTIONS]

    Description:

        xdx : Denotes how many dice to roll and how many sides the dice have.

    The following options are available:

        + - / * : Static modifier

        e# : The explode value.

        ie# : The indefinite explode value.

        k# : How many dice to keep out of the roll, keeping highest value.

        r# : Reroll value.

        ir# : Indefinite reroll value.

        t# : Target number for a success.

        f# : Target number for a failure.

        ! : Any text after ! will be a comment.

 !roll donate : Care to support the bot? Get donation information here. Thanks!

 Find more commands at https://github.com/Humblemonk/DiceMaiden```
