### ISSUE TITLE
Feature Request: Option to unsort dice tally

### ISSUE THREAD

**Issue by ThAlEdison** [Humblemonk/DiceMaiden#14]
Option to show dice unsorted

**Comment by draco963** [comment]
Yes please!!

**Comment by InzPopek** [comment]
Would be great. My DM wants me to make 10 rolls of d20 and wants results unordered. Doing those rolls separately creates a huge mess (takes a lot of space)

**Comment by Humblemonk** [comment]
So I have implemented a way to shuffle the tally. The easiest way to do this is by doing it via a comment. For example:

`[3:17 PM] Humblemonk: !roll 10d20 ! unsort`
`[3:17 PM] BOTDice Maiden: Humblemonk Roll: [9, 11, 10, 14, 17, 16, 1, 2, 0, 6] Result: 105  Reason:  unsort`

By comment ! unsort or !unsort, the tally will be shuffled. This should be live as of now!

**Comment by draco963** [comment]
YAY! Thank you!

**Comment by InzPopek** [comment]
Perfect!
