### ISSUE TITLE
Purge Command Malfunction

### ISSUE THREAD

**Issue by SprinklezWasTaken** [Humblemonk/DiceMaiden#140]
I am attempting to clear a channel that blew up overnight, and Dice Maiden's "purge" function isn't working, it keeps saying "400 Bad Request." What do I do? I need this channel emptied ASAP before I open up again, as it contains spoilers, content that I had NSFW content that I have banned, and various other types of messages I need to clean up before allowing more newcomers to join. I have gone through 100-50 in order to see if the number of purged messages was the issue, but I got the same response over and over:
"Unexpected exception thrown! (400 Bad Request)

Please drop us a message in the #support channel on the dice maiden server, or create an issue on Github."

**Comment by ThatGuyWhatsMadeofCheese** [comment]
This is a bug, but I found a work-around for you.

If you do a roll between each purge, it works.

So, you would do:

!roll purge 100
then 
!roll 1d2
then
!r purge 100
and repeat.

If that doesn't work for you, let me know and I'll see if I can figure something else out so you can clear it tonight :)

**Comment by Humblemonk** [comment]
Hey! Just checking, how old are the messages in the channel? The API endpoint for purging messages will throw a 400 error if the messages are older than 2 weeks.

**Comment by Humblemonk** [comment]
Going to close this one out. Errors with the purge command is typically outside of my control
