### ISSUE TITLE
Dice Maiden should only "purge" messages that initiated a roll and the results

### ISSUE THREAD

**Issue by bytemage** [Humblemonk/DiceMaiden#141]
It's almost a bug, the purge command removes any messages.

It should only remove messages that relate to Dice Maiden. Roll requests and their results. Anything that doesn't fit that pattern must not be touched.

The purge command would be really helpful when rolls and chat are mixed. At the moment it's almost dangerous to use.

**Comment by Humblemonk** [comment]
This is the main reason why I locked the purge command to users with manage permissions or even admin powers, its a pretty powerful command.  Its not that easy to determine which messages to delete and not as its limited by the discordrb api library. At best, it could be limited to just dice maidens messages but that wont really solve the problem. 

Unfortunately theres not much I can do here. Going to close this out as a wont do
