### ISSUE TITLE
Adding A Way To Change Roll Chance

### ISSUE THREAD

**Issue by Firestar9** [Humblemonk/DiceMaiden#142]
**Is your feature request related to a problem? Please describe.**
A few of our players have realy shit luck, and we have non stop really low rolls.

**Describe the solution you'd like**
Can you please add a command to change the chance specific numbers have of being rolled.

**Describe alternatives you've considered**
I guess I can give more bonuses to players, but then it removes the chance of people getting 1s

**Additional context**
Nothing, have a good day all ya'll.

**Comment by Humblemonk** [comment]
Going to close this out as a won't do
