### ISSUE TITLE
Possible to remap syntax

### ISSUE THREAD

**Issue by Sierbahnn** [Humblemonk/DiceMaiden#143]
Hi

I just had to leave Sidekick (as it is experiencing deep connection-issues) leaving me with a LOT of code for dicerolling for Sidekick I would now have to go manually edit in order to get DiceMaiden to read it.
Would it be possible to instruct the bot to "interpret" and thus accept that other syntax?
I mean, I can change /roll to !roll easily enough, but to have to change all 2d20k1 to 2d10 k1 and # to ! for comments would be... Oh gawd... 
Is it possible to "remap" the input of Dice maiden on my end? I am not asking you to remap the syntax for the bot itself, I only need to map it on my end.

**Comment by Humblemonk** [comment]
That would require a fair bit of work. You could fork this repo as well as the dice-bag (relies on it for rolling). Go through the codebase and update the various syntaxs. 

I have no plans to allow users to have personal roll syntaxs/aliases as that would require a lot of database management that I just do not want to deal with.
