### ISSUE TITLE
Add Year Zero dice rolling

### ISSUE THREAD

**Issue by mbirky** [Humblemonk/DiceMaiden#153]
**Is your feature request related to a problem? Please describe.**
No, there is no problem this is an enhancement request.

**Describe the solution you'd like**
As a user, I would like to be able to type `Xyz` -> `Xd6 t6`

**Describe alternatives you've considered**
`Xd6 t6` can be used to 

**Additional context**
In the Year Zero system, you roll a number of D6 equal to the number of points you have and then count the number of sixes rolled.

**Comment by dgerrells** [comment]
I like this one as we use said system in our table top sessions
