### ISSUE TITLE
Unexpected exception thrown! (undefined method `convert_input_to_RPN_queue' for main:Object)

### ISSUE THREAD

**Issue by MRipperWallace** [Humblemonk/DiceMaiden#156]
Issue when running Dice Maiden bot on server Discord server. Error raised:
"Unexpected exception thrown! (undefined method `convert_input_to_RPN_queue' for main:Object)
"

**To Reproduce**
Issue occurs when entering "!roll 1d6" or other dice rolls.
"!roll help" still functions

**Expected behavior**
Error displayed when typing "!Roll 1d6" or any variation there of: "Unexpected exception thrown! (undefined method `convert_input_to_RPN_queue' for main:Object)"

**Comment by Humblemonk** [comment]
Thanks for the report, I believe I know what the issue is. Looking into it now

**Comment by Humblemonk** [comment]
Bot should be good now

**Comment by MRipperWallace** [comment]
Thank you. Also awesome work
