### ISSUE TITLE
Dice Maiden broken in one server only

### ISSUE THREAD

**Issue by ddddddd-hash** [Humblemonk/DiceMaiden#157]
In one specific server of ours, dice maiden has stopped working. It appears online but has no status. It doesn't respond to commands of any type, and the commands still work for other servers. We have kicked, reinvited, and banned/unbanned many times.

**Comment by Humblemonk** [comment]
This might be related to how the discord ruby api handles server caches and communication with the API endpoint. Theres not much I can do here in these situations. Typically the issue resolves itself after a period of time. Removing and re adding the bot can actually make the situation worse :( . 

I spun up additional shards tonight to help with the recent increase activity with the bot. This should alleviate this issue a little bit as well.
