### ISSUE TITLE
Wrath and Glory Exalted Icons

### ISSUE THREAD

**Issue by Perolith** [Humblemonk/DiceMaiden#16]
Would it be possible to allow a second number to count as 2+ successes? for example, in wrath and glory, you roll Xd6, any over 4 gives you 1 success, any 6s give you 2 successes. Maybe add it in as something like (x)p6, where x is how many successes it gives on what number (or higher). If it's possible, you'd be an even bigger hero than you already are for making this. Thanks :)

**Comment by Humblemonk** [comment]
I actually have this implemented for my personal server in the codebase :). Let me see how I can get this working for all servers

**Comment by Humblemonk** [comment]
This has been added. Example roll:

```
1:08 PM] Humblemonk: !roll wng 4d6
[1:08 PM] BOT Dice Maiden: Humblemonk Roll: [6, 5, 4] Wrath: 6 |  TOTAL - Icons: 2 Exalted Icons: 2 (Value:4)
[1:08 PM] BOT Dice Maiden: Combat critical hit and one point of Glory!
```

Syntax is !roll wng . If you do not want to add a wrath dice to the roll, you can use the following comments:
```
! exempt
! soak
! dmg
```
