### ISSUE TITLE
Storypath alias doesn't infinitely explode

### ISSUE THREAD

**Issue by SuPeRJ03** [Humblemonk/DiceMaiden#163]
**Describe the bug**
Pretty much title.  I've been fiddling around with Dice Maiden and have noticed that it doesn't re-re-roll 10s.

**To Reproduce**
Just roll a lot of dice and hope you get lucky enough to explode a 10 off of a 10

**Expected behavior**
Tens should infinitely explode, like so: [10,10,10,3]
Currently, I'm getting this for the "same" roll: [10,10]

Small bug, I know, but it would really help me and my play group out.

**Comment by Humblemonk** [comment]
I got a fix going out today for this. Thanks for the report!
