### ISSUE TITLE
Cleaner Formatting: bold Result

### ISSUE THREAD

**Issue by thoth-process** [Humblemonk/DiceMaiden#166]
**Is your feature request related to a problem? Please describe.**
As a user, I sometimes find it a little hard to specifically and quickly identify the total roll result, since it is in the same font/text as the text around it.

**Describe the solution you'd like**
I would like the roll Result to be formatted in bold.

**Describe alternatives you've considered**
Another alternative could be placing the Result at the end of the text string, after the Reason, but that runs the risk of variable-length Reasons reducing readability for several people rolling in a row.

**Comment by Humblemonk** [comment]
I have added highlighting to results. I think we can close this one out for now.
