### ISSUE TITLE
Cleaner Formatting: @mention roller

### ISSUE THREAD

**Issue by thoth-process** [Humblemonk/DiceMaiden#167]
**Is your feature request related to a problem? Please describe.**
If several people roll at the same time, it can take a bit of extra time to pick out the specific result for the roll you made.

**Describe the solution you'd like**
Where the roller's name is displayed, using an @mention would highlight the result for the roller.

**Describe alternatives you've considered**
None. As far as I am aware, Discord can't do things like use Role/name colors in the body of a message.

**Comment by Humblemonk** [comment]
Closing this out as with slash commands the bot responds directly to the users input. It has a nested structure.
