### ISSUE TITLE
Allow bot to respond in a Channel Thread

### ISSUE THREAD

**Issue by tomsaul** [Humblemonk/DiceMaiden#168]
The bot currently does not respond to a message in Discord Channel Thread (a new feature they just added).  These message are publicly visible, just 'segregated'.  It would be great if this worked - it would help manage clutter in channels.

**Comment by tomsaul** [comment]
Here is the writeup on what is needed to support threads (minimally update to API V9)

https://discord.com/developers/docs/topics/threads

Offhand it is not obvious (to me) if you simply update and start to see the new message notifications if the reply would end up in the parent thread if you don't make other changes to send it using the new 'thread id' part of a response.

**Comment by Humblemonk** [comment]
I really want to implement this but I am still waiting on discordrb to update thread support in their stable branch. Once thats done I can update the bot

**Comment by Humblemonk** [comment]
Thread support is going live today.
