### ISSUE TITLE
Request: Respond to edited messages

### ISSUE THREAD

**Issue by kotarou** [Humblemonk/DiceMaiden#17]
Current behaviour is that when a dice roll (valid or otherwise) is edited, DM does not respond.

It would be nice if when an invalid expression is edited to be valid, DM could recognize the edit, and change its `Incorrect format` report to be the result of the now corrected line.

**Comment by Humblemonk** [comment]
Hey Kotarou,

Closing this out as won't do for now. This is technically not supported right now by the discordrb api library.
