### ISSUE TITLE
Standard advantage and disadvantage are added together

### ISSUE THREAD

**Issue by tyler489** [Humblemonk/DiceMaiden#170]
**Describe the bug**
!roll 3d10 d1 : Roll three ten-sided dice and drop one die. The lowest value will be dropped first. NOTE: These dice are dropped before any dice are kept with the following k command. Order of operations is : roll dice, drop dice, keep dice

!roll 3d10 k2 : Roll three ten-sided dice and keep two. The highest value rolled will be kept.

doing !r 2d20 d1
!r 2d20 +d1
adds all rolls together 

Result: 2d20 (16, 3) + 1d1 (1)
Total: 20

**To Reproduce**
1. Run the command
2. Get result added together

**Expected behavior**
Not to add advantaged or disadvantaged roles together into a total
**Screenshots**

**Additional context**

**Comment by tyler489** [comment]
Dm linked me wrong github

**Comment by ThatGuyWhatsMadeofCheese** [comment]
I see this is closed already, but I'm responding anyway, in case anyone else runs into the same issue and sees this.

This is working as intended, as `!r 2d20 d1` will work as described.

Adding the plus sign, e.g. `!r 2d20 +d1` changes the `d1` from being the drop flag, to being an additional die roll. It's just rolling a one-sided die, and dice maiden assumes you only want a single die rolled, if you don't put a number at the front. So, `!roll d6` will do the same thing as `!roll1d6`
