### ISSUE TITLE
Bot parses dice expressions inside multiline code blocks in messages

### ISSUE THREAD

**Issue by RedwanFox** [Humblemonk/DiceMaiden#172]
**Describe the bug**
Bot parses dice expressions inside multiline code blocks in messages

**To Reproduce**

Open chat with bot.

Send message something like

````
Blablablabla
```
!roll 1d6
```
````

Bot will return dice result

**Expected behavior**
Bot will honor code block and won't execute code from it (as with one line code blocks or quotes)

**Comment by AllieWade** [comment]
I just ran into this too. It appears to have something to do with the command appearing on a new line. (My case was

```Rolling dice goes like this:

!roll 4d6 + 5 s ! Regular check with +5 modifier.
Your basic roll, […]```

and it parsed it as a roll with the entire rest of the code block as a comment.)

**Comment by Humblemonk** [comment]
Fix for this is going out now. The bot should now check not only for the command being at the start of a line but also a start of a string.
