### ISSUE TITLE
Add 'chained command' options

### ISSUE THREAD

**Issue by tomsaul** [Humblemonk/DiceMaiden#174]
Add an operator that allows multiple roll commands in a single invocation.  For example, if '|' was the chain operator

!roll 1d6 + 5 | 1d6

which would show (similar to what you would see with !roll 2 1d6 + 5, but using different rolling rules for each line)

XXX Roll: 
[4] Result: 9
[2] Result: 2

**Comment by tomsaul** [comment]
FWIW- this would be very useful for a number of situations.  For example, when doing dual weapon attacks my command might be 
!roll ul 2 1d20 + 5 | 1d6+5 | 1d6

to determine if I hit with each hand, then the associated damage.  Much easier to do this (with a keyboard macro) than to do the three distinct commands needed now.

**Comment by Humblemonk** [comment]
Working on implementing this now. Chain command will use forward slashes. Roll will look something like this:

/roll 1d6  +5 / 4d6 / 6d12 / 4d10 k2
