### ISSUE TITLE
Drop Highest

### ISSUE THREAD

**Issue by MaxDeBenedetti** [Humblemonk/DiceMaiden#176]
There is currently a way to drop the lowest roll, but not the highest roll. This option would allow for disadvantage in 5e or banes in The Darkest House.

**Comment by AllieWade** [comment]
Try using kl[number]. It stands for "keep lowest," so for instance "!roll 2d20 kl1" keeps the lowest 1 roll, discarding the highest.

**Comment by MaxDeBenedetti** [comment]
Thank you. That definitely helped

**Comment by Humblemonk** [comment]
Closing this out due to recommendation from AllieWade will suffice
