### ISSUE TITLE
Negative Permutations

### ISSUE THREAD

**Issue by falco1029** [Humblemonk/DiceMaiden#18]
I'd love for the bot to be able to !roll # - XdY, e.g !roll 25 - 3d6, to give me a result of 25 minus the result of three six sided dice. I know there's not a lot of systems that do that, but I'm using one of those few now!

Right now I can approximate it with !roll 3d6 - 25 and then invert it, but it doesn't feel as intuitive.

**Comment by Humblemonk** [comment]
Due to how the ruby gem works that the bot relies on for dice rolls, this probably won't be done for some time.

**Comment by Humblemonk** [comment]
With the recent math engine overhaul, this should now be supported!
