### ISSUE TITLE
slash commands

### ISSUE THREAD

**Issue by MisterCookie1234** [Humblemonk/DiceMaiden#182]
**Is your feature request related to a problem? Please describe.**
We are quite unhappy with the current solution, that everyone is able to see the !roll initial commands.
Using the Discord slash commands, that are mandatory in one of the upcoming months, would help a lot.

**Comment by Humblemonk** [comment]
Yep slash commands are in the works. Stay tuned!

**Comment by MisterCookie1234** [comment]
Any ETA? :)

**Comment by MisterCookie1234** [comment]
Hello! Any updates?

**Comment by Humblemonk** [comment]
Slash commands went live today.
