### ISSUE TITLE
Rerolls not working with multiple dice

### ISSUE THREAD

**Issue by Furyfoggy** [Humblemonk/DiceMaiden#187]
For some reason, when you have multiple types of dice to Reroll, it doesn’t actually Reroll most of them.

I used commands like “!roll 6d4 r2 + 2d6 r2 + 1d4 + 6” and it didn’t reroll any of them or very few of them, because I was still experiencing 1’s and 2’s. 

I expected it to reroll each individual dice that had a 1 or 2 on it, which it either didnt do or didn’t display that it did on the “Rerolls:” part of the output.

**Screenshots**
![58F1407B-E90A-4C83-8E63-BFB16ECDD5EE](https://user-images.githubusercontent.com/101444417/158004965-b460c234-737f-4d6b-8ba7-992c78187f55.jpeg)
![4CD9793A-327D-42D3-885D-C18D56108F4F](https://user-images.githubusercontent.com/101444417/158004966-180dc87d-6945-4d50-9378-17abcf8d72be.jpeg)
![45512DC3-32AD-4C0C-A140-70E82F4F7E03](https://user-images.githubusercontent.com/101444417/158004967-d08a2ae8-81db-4bab-a35d-c2016c614937.jpeg)

**Comment by Humblemonk** [comment]
Thanks for reporting this issue. I think If found the issue with multi dice roll syntaxes, we are currently only checking the last part of the roll for the reroll value. I am updating this today to check all parts of the roll syntax
