### ISSUE TITLE
Use pinned messages to store dice roll aliases

### ISSUE THREAD

**Issue by AncientSwordRage** [Humblemonk/DiceMaiden#188]
Custom alias for rolls could put strain on the server running dice maiden.

But using pinned messages to store them per channel would alleviate some of the burden.

This closes issues has a good starter for alias commands:

https://github.com/Humblemonk/DiceMaiden/issues/106

This idea would mean using `!dm alias d6system /d6s(\d+)d/ '$1d6 + 1d6 ie' ` would put a pinned message into the current channel that was `d6system /d6s(\d+)d/ '$1d6 + 1d6 ie' `

You'd use a special prefix to tell dice maiden it was an aliases command.

Everything else should flow from there.

**Comment by Humblemonk** [comment]
Closing this out as won't do as the bot is forced to use slash commands
