### ISSUE TITLE
Complete Earthdawn rolls

### ISSUE THREAD

**Issue by MrDHOLE** [Humblemonk/DiceMaiden#189]
Hi there ! I'm glad to find out that Dicemaiden includes Earthdawn rolls (!roll edX, where X is the step). Sadly those are only for the 20 first steps.

Could you consider adding the missing 20 steps (21-40) ? Doesn't seem like too much of a hassle, and it could help out with ED players, all along their campaigns, without stopping at some point.

Kind regards,
FØX

![image](https://user-images.githubusercontent.com/99138902/161436458-cc095dbc-fade-4ba2-8287-b9318a17c891.png)

**Comment by MrDHOLE** [comment]
Actually it goes up to 50, my bad...

![image](https://user-images.githubusercontent.com/99138902/162632378-8b83d31b-dc6f-400a-9b58-d60158b465a5.png)

**Comment by Humblemonk** [comment]
This is getting merged today
