### ISSUE TITLE
bot disallows d2

### ISSUE THREAD

**Issue by nonchip** [Humblemonk/DiceMaiden#19]
> nonchip: !roll 20d2
> [BOT]Dice Maiden: Please roll a dice value 3 or greater

probably because of [this](https://github.com/Humblemonk/DiceMaiden/issues/7#issuecomment-484344870), but while "disallow < `d2`" (like you said) would've made sense, "disallow <= `d2`" (like you did instead) doesn't. coins are a thing, and systems want me to toss them.

**Comment by Humblemonk** [comment]
I believe I went with d3 or higher due to the bot hanging on not only d1 rolls but d2 as well. I will look into it.

**Comment by nonchip** [comment]
i actually settled with just writing my own bot instead because i wanted some other unrelated features and don't like throwing a million bots on my server, so afraid i don't technically need it anymore :P

still should probably be fixed, and if it hangs on d2 that's probably a different/underlying issue then that would benefit being fixed instead of circumvented, since lots of RPG systems and also just simple "who's job is organizing suchandsuch" questions between users involve coins

**Comment by Humblemonk** [comment]
This is now resolved
