### ISSUE TITLE
Bot doesn't listen in threads sometimes?

### ISSUE THREAD

**Issue by cahe** [Humblemonk/DiceMaiden#195]
![image](https://user-images.githubusercontent.com/3882/170953647-2f83d0f0-321b-4b18-9727-9c4a57d6d56e.png)

d20 roll made by server admin

Bot joined the thread after admin rolled d20

**Comment by Humblemonk** [comment]
Threads are still a bit experimental with discordrb and have stability issues. Closing this out as there's not much I can do here as its an API library issue.
