### ISSUE TITLE
Request: Assign DM per Channel

### ISSUE THREAD

**Issue by mathewdegauven** [Humblemonk/DiceMaiden#197]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to assign a user elevated privileges on a per channel basis. Assigning a DM could allow additional DM only features like the ability to roll privately (and then share the results with a reaction), or a DM only version of `!dm request show ` where the request is only shown to the DM, or a method to list the last X rolls and results in a single message.

**Describe the solution you'd like**
I would like the ability to assign user(s) to a DM roll per channel to enable DM specific features.

**Describe alternatives you've considered**
This could possibly be completed with Discord's roles and permissions. Create a role called `channel-dm[0-100]` and give it `manage messages` or `administrator` access to one or more channels. Assign users to the role to give them the DM role. DiceMaiden could look for the role naming convention to provide extended features to DMs in channels where the role is assigned.

**Additional context**
This would extend the ability additional DM specific features that don't currently exist.

**Comment by Humblemonk** [comment]
private rolls are supported in a couple of ways right now. You can do rolls in a channel locked down to select users or private message the bot. Closing this out as a won't do as further private rolls is not something I want to support/maintain
