### ISSUE TITLE
Request: Additional Request Show options

### ISSUE THREAD

**Issue by mathewdegauven** [Humblemonk/DiceMaiden#198]
**Is your feature request related to a problem? Please describe.**
Currently, if `!dm request show` is  enabled, it adds the text to the end of the message which can confuse less technical users and distract from the result.

**Describe the solution you'd like**

- `!dm request show self` 
  - Send a private message showing the request, or a channel message that only the user can see with the request and roll.
- `!dm request show dm`
  -  Send a private message showing the request and result to the DM.
  - May require extended DM functionality. https://github.com/Humblemonk/DiceMaiden/issues/197
- `!dm request show reaction` 
  - Reaction to check the request if triggered.

**Describe alternatives you've considered**
An alternative that would make this command would be to add the request text as a new line instead of at the end of the result line. This would separate the result from the request enough to make it easier to read without getting in the way of the result.

**Comment by Humblemonk** [comment]
Closing this out as wont do as slash command move makes this functionality extremely hard if not impossible to implement :(
