### ISSUE TITLE
Request: List last X rolls

### ISSUE THREAD

**Issue by mathewdegauven** [Humblemonk/DiceMaiden#199]
**Is your feature request related to a problem? Please describe.**
Currently the only way to view rolls concisely is to scroll through messages. This can be challenging if there is a lot of discussion happening. 

**Describe the solution you'd like**
`!dm list [1-10]` would list the last [1-10] rolls and results in a single message.

**Describe alternatives you've considered**
One alternative might be the ability to subscribe to a channel's rolls and receive a private message for each roll. This would at least allow a user to have a private message log of rolls.

**Additional context**
This feature could benefit from extended DM permissions as requested here: https://github.com/Humblemonk/DiceMaiden/issues/197

**Comment by Humblemonk** [comment]
As much as I think this would be a good thing to implement, I am going to close this out as won't do as it would require caching of data on a per-server basis and the bot is already extremely resource-constrained with ~400k active servers.
