### ISSUE TITLE
REQUEST: Support for Tunnels and Trolls DARO/TARO

### ISSUE THREAD

**Issue by sirkerry** [Humblemonk/DiceMaiden#20]
A feature to consider:
The game system Tunnels and Trolls has a thing similar to exploding dice, but slightly different. It's doubles and triples of the same value rolled get added and rolled over.

If possible, would be a nice feature to add.

**Comment by Humblemonk** [comment]
Hey sorry for the very much delayed response. This is a pretty unique scenario and would require a fair bit of rewriting the dice rolling mechanics of the bot to support. Going to close this out as won't do
