### ISSUE TITLE
Request for Chronicles of Darkness

### ISSUE THREAD

**Issue by kkswsa** [Humblemonk/DiceMaiden#200]
**Describe the solution you'd like**
I would like to request 2 additional commands for Chronicles of Darkness.
A 9 and 10 explosion and a 8,9, and 10 explosion.
Maybe something like this? TY for your time and consideration.
4cod9 -> 4d10 t8 ie9    
4cod8 -> 4d10 t8 ie8

**Comment by boredcity** [comment]
added PR to add this aliases, hopefully it gets merged 🤞

**Comment by Humblemonk** [comment]
This will be going out today to the bot
