### ISSUE TITLE
Breaks on mobile

### ISSUE THREAD

**Issue by ThunderWasTaken** [Humblemonk/DiceMaiden#203]
**Describe the bug**
Trying to use the / commands on mobile does not allow you to use custom dices such as 1d20+4 or 6d8 for example

**To Reproduce**
1. Go to Discord Mobile
2. Type /roll
3. Try to put 1d20+4 or more on it
4. It will either send it as a text message or just ignore it completely or put it as a message

**Expected behavior**
For it to roll 1d20+4, not just 1d20 and put 1d20+4 on the message.

**Screenshots**
Not necesarry

**Additional context**
The / command broke Dice Maiden on mobile

**Comment by Humblemonk** [comment]
So this isnt a Dice Maiden bot issue but more of a Discord mobile UI/UX issue. The recommendation I have here is to do the following:

1.  type /roll or /r
2. click on the slash command that you are prompted with for the bot
3. click on the message option
4. type 1d20+4 or whatever roll you want to do

The command should work as expected. This is just another example of the negative aspect of slash commands and its not something I can change or control. I would suggest providing discord feedback  here: https://support.discord.com/hc/en-us/community/topics
