### ISSUE TITLE
YES/NO command

### ISSUE THREAD

**Issue by Doroshi-pl** [Humblemonk/DiceMaiden#204]
Is it possible, sometime in the future, to add a command that will give a YES/NO answer? E.g. even numbers are YES and odd numbers are NO.

Right now I use the command /roll 3d100 and if there is a majority of even then YES, if there is a majority of odd then NO.

NP. 
Rolls [1], **[2]**, [3] result = NO.
Rolls [1], [3], [5] result = NO

Rolls [2], [4], [6] result = YES
Rolls [2], **[3]**, [4] result = YES.

I don't take into account the result of the sum because it wouldn't be random.  Because two odd numbers summed gives an even result. 

In the attachment I gave screeen, from the application of the bot.
![unknown](https://user-images.githubusercontent.com/112462536/187385835-389b0800-0d6c-4273-8e82-4ff3f3fa886f.jpg)

Sincerely, Dorota

**Comment by keepinitriehl** [comment]
Can't you just roll 1d2?

**Comment by Humblemonk** [comment]
I am going to close this out as a wont do as I do not feel like supporting it. If anyone else wants to implement this, they are more than welcome to send in a pull request.
