### ISSUE TITLE
Rolling Through DMs Gives Last Character (globally) Rolled as Name

### ISSUE THREAD

**Issue by KiriKaz** [Humblemonk/DiceMaiden#211]
**Description of bug**
When using a roll command with Dice Maiden in the DMs, it rolls normally, but the character/person's name is replaced with the last roll the bot gave for anyone using the bot in a server, leading to some potentially awkward surprises.

**To Reproduce**
1. Open DM with Dice Maiden.
2. Roll any valid roll. Used in the example is `2d20`.
3. Observe the error message. Your name is replaced with the last user who rolled with the bot in a server.
4. If you roll again, you may observe the same name, or it will be replaced with whoever most recently rolled the bot in a server.

**Expected behavior**
Dice Maiden should use my username when rolling in DMs.

**Screenshots**
<img width="546" alt="image" src="https://user-images.githubusercontent.com/6729536/208298170-e5a0cfac-6911-4646-a6dc-38e6061d47ba.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/6729536/208298179-7573e80b-325a-46f7-b06b-4fcde6ff32e1.png">

**Additional context**
Further rerolls do not replace the username.

**Comment by Humblemonk** [comment]
Well thats an unfortunate new one. Ill take a look at this today

**Comment by Humblemonk** [comment]
Resolved here c888eab796a82e89b46513f6d0120f7cb4d19f3d

**Comment by KiriKaz** [comment]
Looks like there's a typo in your commit, beyond that, looks good! Thanks for fixing it.
