### ISSUE TITLE
Roll requests occasionally showing username instead of display name

### ISSUE THREAD

**Issue by reaperzeus** [Humblemonk/DiceMaiden#219]
**Describe the bug**
For certain users on our server, when they make a /roll request, the bot's response of ex. "____ Request: [1d100] Roll: [90] Result: [90]" the blank space will include their Discord Username rather than their Display Name or Server Profile.

**To Reproduce**
1. Send a /roll request, eg `/roll 1d100`
2. Check what name it uses in the response

**Expected behavior**
For most users the name listed for the request is the Display Name or Server Profile

**Screenshots**
Usernames redacted for privacy reasons
![image](https://github.com/Humblemonk/DiceMaiden/assets/115575697/d67d9285-76c1-42fd-b12b-4c56ec44c076)

**Additional context**
- One user is the server owner but the other is not.
- This is a potential privacy concern, especially as it does not get hidden by Discord's Streamer Mode when programs like OBS are launched

**Comment by Humblemonk** [comment]
Hmm I wonder if the recent changes to usernames borked this. I will take a look

**Comment by Humblemonk** [comment]
Going to push a minor update for this to see if it resolves the issue. If it doesnt, I might have to wait on an update to the discordrb library :/

**Comment by Humblemonk** [comment]
Ok so actually I think this is working as intended. The logic right now is the bot will default to the nickname set for the server and if none is set, it will use the username instead.

**Comment by reaperzeus** [comment]
Can the logic be chained to go Server Nickname -> Display Name? Before it didn't show the #xxxx so privacy with it wasn't an issue but now it _might_ reveal something (unlikely I know but I figure it's a worthwhile possibility to consider)
