### ISSUE TITLE
Have an option to keep the lower results instead of higher

### ISSUE THREAD

**Issue by Frozedon** [Humblemonk/DiceMaiden#22]
Like rolling disadvantage in D&D 5e

**Comment by wishinghand** [comment]
Played a PBtA game tonight and rolling advantage is 3d6 k2; disadvantage is 3d6 k2 but it's the bottom two. We made do but could have definitely used a `kb` or something like that.

**Comment by Humblemonk** [comment]
This should get the job done: 

`!roll 4d10 kl3 `: Roll four ten-sided dice and keep the lowest three dice rolled. NOTE: This modifier will only work with comments and math modifiers
