### ISSUE TITLE
In a campaign right now, and dice maiden is not working. 

### ISSUE THREAD

**Issue by technosorcerer** [Humblemonk/DiceMaiden#221]
**Describe the bug**
We do simple commands and the bot responds with !The application did not respond

**To Reproduce**
1. Be on discord
2. type /roll
3. Select the dice maiden window prompt
4. try to roll any dice

**Expected behavior**
Dice to be rolled

**Screenshots**
![sc](https://github.com/Humblemonk/DiceMaiden/assets/80850797/a2844c84-15d0-49ba-82b3-a7bc92f3a71a)

**Additional context**

**Comment by Humblemonk** [comment]
Hey Technosorcerer, I posted this on the support discord server:

I am currently traveling for work and during this time the server that the bot is hosted on is having a hardware failure issue. Being 3000 miles away, I am unable to resolve this issue until this weekend. Timing is unfortunate :( 

In the meantime I recommend using alternative bot until I can get dice maiden up and running again. Here are two alternatives 

I recommend dice parser: https://top.gg/bot/279722369260453888 or Bogsy dice bot https://top.gg/bot/812347275698634762 


Sorry for the outage. First major one in 7+ years :/

**Comment by Humblemonk** [comment]
The bot will be back online this saturday

**Comment by tomsaul** [comment]
Thanks - and it is worth pointing out that since this is open source, anyone is free to create and host the bot on an alternative server.

**Comment by technosorcerer** [comment]
Thank you!!!

**Comment by Humblemonk** [comment]
Bot is coming back online now
