### ISSUE TITLE
cod8/cod9 aliases inverted

### ISSUE THREAD

**Issue by VerteDragonne** [Humblemonk/DiceMaiden#223]
While getting used to and setting up for my campaign, I noticed #cod9 rolls for 8-Agains and #cod8 rolls for 9-Agains.

**To Reproduce**
Simply roll something with high dice, to mostly ensure you have a spread fo 10s to 8s. Examples, /r 10cod9 or /r 10cod8.
The cod9 will reroll 8s, 9s, and 10s, while cod8 will reroll 9s and 10s.

**Expected behavior**
Per the examples above, cod9 should reroll 9s and 10s, while cod8 should reroll 8s, 9s, and 10s.

**Additional context**
This is confirmed within the source.
dice_maiden_logic.rb lines 18 and 19 show the two commands to be inverted.

**Comment by Humblemonk** [comment]
Ah this should be an easy fix. Ill give this one done today. Thanks for sending it in!

**Comment by Humblemonk** [comment]
Fix is going out now
