### ISSUE TITLE
Translation request

### ISSUE THREAD

**Issue by OneEyedTiamat** [Humblemonk/DiceMaiden#226]
**Is your feature request related to a problem? Please describe.**
A Discord server I'm a member of uses Dice Maiden but many people don't speak English that well. Would it be appropriate to translate the documentation (at least the readme) and post it here?

**Describe the solution you'd like**
Ideally, I'd like the user manual to be available in more languages. I can do a French version.

**Describe alternatives you've considered**
I have a quick translation of the user manual I can improve on. I posted it in the relevant server.

**Additional context**
I'm more or less bilingual when it comes to written English.

**Comment by Humblemonk** [comment]
Hey @OneEyedTiamat , if you wish to write a french version of the readme, you can submit the change as a pull request. If you do not know how to do that, I am more than happy to review it here ( google drive link for example)

**Comment by Humblemonk** [comment]
Actually, closing this out. Just hit me up on Discord via the support channel if you wish to continue this initiative
