### ISSUE TITLE
Application no longer working on one server

### ISSUE THREAD

**Issue by OneEyedTiamat** [Humblemonk/DiceMaiden#227]
**Describe the bug**
My club uses Dice Maiden on two servers. It works on the smaller one, but I get an error message on the bigger one: "The application did not respond"
I tried the command roll 1d20 with a / before roll. The exact same command works on the smaller server.

**To Reproduce**
I tried the command roll 1d20 with a / before roll. On one server, it works, on the other, I get the error message.

**Expected behavior**
I expected the same command to get the same reaction.

**Screenshots**
![Screenshot_20240115_110840_Discord](https://github.com/Humblemonk/DiceMaiden/assets/101602273/246c1485-6674-43c2-b066-b96f2d630bba)
result of /roll 1d4

![Screenshot_20240115_111257_Discord](https://github.com/Humblemonk/DiceMaiden/assets/101602273/6b7b6879-43d4-4b31-96ac-fd292fdbbbe3)
Result of /roll 1d4 test

**Additional context**
I'm a member of a smallish French TTRPG  org/club. The bot works for a campaign server, but not the main server.

According to the person maintaining our server, it's likely a settings issue. Uninstalling and reinstalling didn't fix the issue.

**Comment by OneEyedTiamat** [comment]
Hello?

**Comment by Humblemonk** [comment]
Hey  so this isnt really a bug with the bot but more an issue with the discordrb library and the discord API backend. Theres not much I can do here, sorry! Closing this one out
