### ISSUE TITLE
Hidden player roll-s

### ISSUE THREAD

**Issue by DJRafi01** [Humblemonk/DiceMaiden#229]
It's usefull thing to some DM-s to let players make some roll-s made by them unknown to them, nice idea would be to make for example channel which would be for such rolls for example
normal roll would be normally rolled on same chat but secret rolls would go only to chat designated for them earlier by command which would be visible only for gm and DiceMaiden in matter of permissions

**Comment by Humblemonk** [comment]
Wouldnt it just be easier to create a channel and set permissions correctly and have the user roll in that channel instead of the "public" channel? I don't see the need to implement this on the bot when your server admin could spend a few cycles to setup channel permissions
