### ISSUE TITLE
Single Die Rolls in the D6 System

### ISSUE THREAD

**Issue by DeafKhan** [Humblemonk/DiceMaiden#230]
Attempting to roll a single die using the D6 system syntax doesn't produce expected results.

Using a command of "/roll d6s0" rolls 2D (one standard D6, and one wild die that explodes on 6 as expected).

Attempting to use "/roll d6s" does roll 1D, however the die just a standard D6 (i.e., does not explode on a 6).

Current work around is to use "/roll 1d6ie" instead.

**Comment by Humblemonk** [comment]
![image](https://github.com/Humblemonk/DiceMaiden/assets/12452024/da6ac487-f27c-4bf3-910e-f6a45a9d52f1)

Looks like I got it working in my test branch. Will try and merge it shortly
