### ISSUE TITLE
Request: Add a number for every throw in a series

### ISSUE THREAD

**Issue by T30G10v4** [Humblemonk/DiceMaiden#235]
Hi all,
First of all i want to thank all the developers involved in this project, it's a great instrument.
For my D&D sessions, it will be great to sum a modifier for each dice thrown
For example, if I launch 4d20 ++3 (proposal of command), the result will be
20+3, 18+3, 17+3, 9+3.
This is great for massive attack throw.
Thank you

**Comment by Humblemonk** [comment]
Solid idea! I will look into this

**Comment by Humblemonk** [comment]
Actually, wouldnt this be possible today by rolling a set? For example:
/roll 4 d20 +3
results:
[3] Result: 6
[20] Result: 23
[6] Result: 9
[16] Result: 19

Roll 4 d20 dice and add 3 to each roll

**Comment by Humblemonk** [comment]
Going to close this out for now as I think roll sets does this well enough
