### ISSUE TITLE
Provide an option to only ever reroll a single dice once.

### ISSUE THREAD

**Issue by jasarien** [Humblemonk/DiceMaiden#24]
Some gaming systems, for example Warhammer 40K, have rules that only allow a single die to be rerolled once.

When using the `r` option, Dice Maiden will happily reroll the dice until the value is greater than the reroll threshold. This breaks the rule in the gaming systems that only allow one reroll per dice.

I was thinking maybe an option such as `r1` could be added to only reroll a single die once and thereby keep within the rules for those systems.

I think the same could be done with the `e` option as well. Eg, the DAKKA! DAKKA! DAKKA! rule in WH40K says that any rolls of a 6 generate an extra shot, but 6s on those generated shots cannot themselves generate another shot.

I hope this makes sense!

**Comment by Darkade** [comment]
Yes, it'd be nice to be able to reroll just once, particularly with the explode option

**Comment by ShadowGamer3** [comment]
On a similar note, when building characters for Pathfinder, when we roll stats for Str, Dex, etc. we roll 4d6, re-roll 1's every time they appear, and 2's just the first time

Example: 
!roll 4d6

Result: 6, 4, 2, 1

we would re-roll the 1 until it's not a 1 anymore, and re-roll it if it turns into a 2, but only the first time it's a 2

then we would re-roll the 2, but if it hits 2 again at any point, it's stuck there.  However, if it turns into a 1, then it gets re-rolled until it's not a 1 anymore.


Possible command for this:

!roll 4d6 ri1 r2-1

ri# = re-roll this number every time it appears
r#-# = re-roll the first number up to the second number of times (if if doesn't show up that many times, then that's fine.

when done this way, only re-roll the specified numbers, and no others.

**Comment by Humblemonk** [comment]
This should now be resolved with the recent changes to how rerolls work with the bot.

**Comment by Humblemonk** [comment]
Going to close this issue out. If any new problems pop up with rerolls, please create a new issue! :)

**Comment by jasarien** [comment]
Sorry for not replying! It sounds like you’ve resolved the issues. I’ll test it when I can and let you k ow if there’s anything wrong. Cheers!
