### ISSUE TITLE
"0" in !unsort result

### ISSUE THREAD

**Issue by InzPopek** [Humblemonk/DiceMaiden#25]
As written in the quoted example, one of the rolls is always 0 when using !unsort, and the sum is wrong (try rolling: !roll 2d20 ! unsort):

`[3:17 PM] Humblemonk: !roll 10d20 ! unsort`
`[3:17 PM] BOTDice Maiden: Humblemonk Roll: [9, 11, 10, 14, 17, 16, 1, 2, 0, 6] Result: 105  Reason:  unsort`

_Originally posted by @Humblemonk in https://github.com/Humblemonk/DiceMaiden/issues/14#issuecomment-552028446_

**Comment by Humblemonk** [comment]
Thanks for letting me know! I will try and look into this over the next couple weeks.

**Comment by Humblemonk** [comment]
This should now be resolved.
