### ISSUE TITLE
D20 +/- Boons & Banes - Shadow of the Demon Lord

### ISSUE THREAD

**Issue by TomCadorette** [Humblemonk/DiceMaiden#26]
In the game Shadow of the Demon Lord, you modify your d20 roll with Boons or Banes (Boons add, Banes subtract). Essentially you roll multiple Boons or Banes (never both, as they cancel each other out).  Only the highest Boon or Bane is used, so it would be something like:

Roll w/2 Boons: 1d20 + (2d6 k1), example 18, (6, 1), result = 24

Roll w/2 Banes: 1d20 - (2d6 k1), example 18, (6, 1), result = 12

Except that the syntax doesn't function like that nor does it use parens. 

Is this something that can be built in? It works in reverse with the Boons/Banes in front of the roll, but then you can end up with negative numbers even if d20 well exceeds Bane minus roll.

**Comment by Humblemonk** [comment]
Hey! Based on the syntax examples you provided. This is now supported:

[12:08 AM] Humblemonk: !roll  1d20 + (2d6 k1)
[12:08 AM] BOT Dice Maiden: Humblemonk Roll: [9][6, 6] Result: 15
