### ISSUE TITLE
The e option does not work

### ISSUE THREAD

**Issue by Maxmech** [Humblemonk/DiceMaiden#3]
The 'e' extension to !roll does not seem to do anything, I am assuming by explode you meant ignore. If I am wrong about that, can you describe what it is for in a different fashion?

**Comment by Humblemonk** [comment]
Hey Maxmech, I will look into and get back to you. It should explode and not ignore.

**Comment by Humblemonk** [comment]
Hey Max, can you give me an example syntax you are trying which is failing?

**Comment by Maxmech** [comment]
Explode... What does that mean?

**Comment by Humblemonk** [comment]
If the number rolled is greater than or equal to the value given for this option, the die is rolled again and added to the total. If no number is given for this option, it is assumed to be the same as the number of sides on the die. 

I just tested it and it looks like it is working!
