### ISSUE TITLE
Different dice must be able to have a separate explode threshold

### ISSUE THREAD

**Issue by CordAm** [Humblemonk/DiceMaiden#30]
This is an issue for all RPGs, which need exploding dices, if the highest dice result is is rolled

Example of the Problem:
***
!roll 2d6 e6 + 1d4 e4

BOT Dice Maiden:
Incorrect format
***

Expected Result, e.g.:
***
!roll 2d6 e6 + 1d4 e4

BOT Dice Maiden:
[6,4,3] [4,1]
***

**Comment by SalieriC** [comment]
+1

**Comment by mzywiol** [comment]
+100 !!! I can't play EarthDawn using Dice Maiden without this.

**Comment by Humblemonk** [comment]
With the recent updates to the bot, this is now supported! Re open this issue if you run into any problems :)
