### ISSUE TITLE
REQUEST: Rerolls

### ISSUE THREAD

**Issue by SalieriC** [Humblemonk/DiceMaiden#31]
Adding reroll as a feature to automatically reroll the last roll the user has made, example:
```
!roll d8 e8
[3] Result: 3

!roll reroll
[8, 3] Result: 11 (reroll of: d8 e8)
```
This way the !roll reroll command could be kept in the clipboard for ease of use if different dice rolls are made each time. Even simpler would be !reroll if that's possible.

**Comment by Humblemonk** [comment]
The work required to add support for rerolls would be nontrivial and would be a pain to support on very large discord servers. Going to close this out as a won't do for now, sorry!
