### ISSUE TITLE
Secret Rolls for GM

### ISSUE THREAD

**Issue by allenroulston** [Humblemonk/DiceMaiden#32]
I don't know whether or not this can be accomplished, or exists already, however searches, thus far, do not reveal the ability for the GM/DM to make a SECRET roll, not displayed to the players.

Ideally, it would be nice for the GM to be able to make a secret roll within DiceMaiden.

Thank you,
~ Allen

**Comment by R0ckL0bster** [comment]
I made separate GM channel and roll there.

**Comment by Humblemonk** [comment]
No plans to implement something like this. Best route is the recommendation above which is to create a GM only dice rolling channel.

**Comment by Humblemonk** [comment]
I just wanted to add, this functionality is not supported yet by Discord or the ruby Discord API library. No idea when it might get supported so closing it out for now.
