### ISSUE TITLE
Maybe unintended behaviour in r2 (r#)

### ISSUE THREAD

**Issue by KomaGR** [Humblemonk/DiceMaiden#35]
Using `!roll 2d4 r3` will result in dice that come up 1, 2 or 3 being rerolled **infinitely**. I think a most useful usecase would be to reroll them once (e.g. for Great Weapon Fighting style in 5e).

Is what is currently happening any different from just rolling a dice with less sides and then adding a modifier? What I mean is that, currently:
```
!roll 2d6 r2 == !roll 2d4 +4
```
This is similar to #24 but different in that I actually claim the current behaviour to be wrong.

**Comment by scottlafetra** [comment]
I can probably address this when I revamp exploding dice next week. I'm thinking of making "indefinite" version of some commands. So `r#` would be "reroll #" and `ri#` would be "Reroll # indefinitely".

**Comment by KomaGR** [comment]
Consider also rerolling the specific side i.e. 

- `!roll 1d6 r2` rerolls only the first 2 that comes up. 
- `!roll 1d6 r1r2` rerolls 1s and 2s of the initial roll. *
- `!roll 1d6 r2r6` rerolls 2s and 6s of the initial roll. *
- `!roll 1d6 r2r2` would reroll a 2 and if 2 comes up on the reroll it would reroll that, too.

* Here if a reroll of a 1 rolls a 2, or a reroll of a 2 rolls a 1 it should not be rerolled. That means we always accept the reroll.

**Comment by Auctorion** [comment]
> I can probably address this when I revamp exploding dice next week. I'm thinking of making "indefinite" version of some commands. So `r#` would be "reroll #" and `ri#` would be "Reroll # indefinitely".

This would be exceptionally useful as there is currently no way to adequately replicate the Rote rolls in CoD without manually typing multiple roll commands. Slows the pace of games.

**Comment by Humblemonk** [comment]
This should be good to go. We just released support for two types of rerolls by moving indefinite rerolls to a new command: `ir`.

**Comment by KomaGR** [comment]
I see it. That's great!

It would also be helpful to provide feedback as to whether a reroll happened. Right now the roll result list only shows the keeped roll, I think.

**Comment by scottlafetra** [comment]
Already have you covered. The overhaul should make it so the results display as: [1, 2, 3, 4] [2]

**Comment by Humblemonk** [comment]
Going to close this out by the end of the week
