### ISSUE TITLE
Allow parenthesis to indicate order of operations

### ISSUE THREAD

**Issue by ViridianImpact** [Humblemonk/DiceMaiden#37]
for example a character needs to succeed a saving throw of 17 Dex so the player inputs
!roll (1d20 + 7) t17

the program does the roll, adds the 7, then checks if it is a success or not

**Comment by Headhunter242** [comment]
This allows for more combinations, it's a good suggestion.

**Comment by Humblemonk** [comment]
With the recent update to the bot, this should now be working! Please re open this issue if you notice a problem. Thanks!
