### ISSUE TITLE
REQUEST: Add an alias "!roll dx" to "!roll 1dx" if possible

### ISSUE THREAD

**Issue by orestisfra** [Humblemonk/DiceMaiden#4]
Hey! This is an amazing bot you made! Is it possible to add an alias command that when you type "!roll dx" make the bot execute "!roll 1dx" ? (e.g. "!roll d6" . "!roll 1d6" will still work though). If you think that this is gonna cause trouble or slowdown ignore this request. This is more to improve ease of use.

Thanks!

**Comment by Humblemonk** [comment]
Hey! Glad to hear you are enjoying the bot. I can see the value in this minor tweak. Let me look into it.

**Comment by Humblemonk** [comment]
This has been added.
