### ISSUE TITLE
Request: Advanced Exploding Dice

### ISSUE THREAD

**Issue by Headhunter242** [Humblemonk/DiceMaiden#40]
Current Situation is not handy for exploding dice. The unsort option makes it a bit better.
Exploding dice only explode once. For Shadowrun 3rd, they need to keep exploding.

Suggestion 1 split the exploded roll

!roll 5d6 e6 !s(plit)
[6, 6, 5, 3, 2, 2][6, 4][3]

Suggestion 2 add the exploded rolls together

!roll 5d6 e6 !a(dd)  (same roll result as above)
[15, 10, 5, 3, 2, 2]

This allows for rolls against a target number

!roll 5d6 e6 !a(dd) t7  (same roll result as above)
[15, 10, 5, 3, 2, 2] 

For Shadowrun we're not always interested in the sum of the rolls, therefore I suggest an operator in the same way as to remove the tally.

**Comment by TashaGrn** [comment]
VTM and Savage worlds also have dice that keep exploding as long as they are above the expode threshold.

**Comment by SmilingBanditUK** [comment]
Shadowrun 2e is the same.

I have an additional request to piggy back onto this.  I have tweaked the rules for Exploding Dice in my ongoing 2e game.  The exploding dice are d6-1 (0-5), and Explode again on the highest roll (5).  So a dice could roll 6, 5, 5, 3 and be a total of 19, against a target number of X.  Is there any way to achieve this with your amazing creation?

**Comment by nitro01** [comment]
this would be wonderful. 
i can only support this request. we are playing shadowrun 4th and have the same problem. in some cases you have to roll some 11's or something and you have to do !roll Xd6 e ! unsort - but you also have to add the numbers up yourself to see, if and how many successes you had.

and while you are on it: please think about adding a modifier that enables you to cap the number of explosions of a single die. (like in "this d6 explode if they roll over 4, but only twice max" - so the max-number per dice would be 18.

**Comment by Humblemonk** [comment]
This should be good to go. We just split up the explode command into two separate commands: one that explodes once `e` and one that explodes indefinetely `ie`. The explosions are split in the tally. Example below:

```
[12:27 PM] Humblemonk: !roll 20d6 ie6
[12:27 PM] BOT Dice Maiden: Humblemonk Roll: [6, 6, 6, 6, 6, 5, 5, 5, 4, 4, 4, 4, 3, 3, 3, 3, 2, 2, 1, 1], [6, 6, 6, 5, 1], [6, 4, 1], [4] Result: 118```

**Comment by Humblemonk** [comment]
Going to close this out by the end of the week

**Comment by Headhunter242** [comment]
Thanks for the indefinitely exploding dice. What about my suggestion to make the sum of the exploding dice, is this something you're going to implement?

**Comment by Humblemonk** [comment]
At this time we do not have any plans to separate the tally results at the end of the roll
