### ISSUE TITLE
roll purge does not seem to work

### ISSUE THREAD

**Issue by BillKills974** [Humblemonk/DiceMaiden#41]
Hi,
roll purge x does not seem to work. When attempting to purge an amount of messages within valid range, bot does neither purge the amount of messages, nor reply that user is not authorized. I tried using a non-valid amount, the expected reply appears correctly ('Amount must be between 2-100').
There is something going on with that authorization check.

EDIT: apparently channel.prune(amount) is not defined in discordrb

**Comment by BillKills974** [comment]
BTW, I think you should also check for effective authorizations including channel overrides using 
#permission?(action, channel) with channel not nil, instead of #defined_permission?(action, channel = nil)

**Comment by Humblemonk** [comment]
Working on a fix for this. Should be out within the next day or so.

**Comment by Humblemonk** [comment]
Ok so this should be fixed now. the purge command should check for server roles as well as channel permissions now.
