### ISSUE TITLE
Support for 1D66 with two D6 dice.

### ISSUE THREAD

**Issue by R0ckL0bster** [Humblemonk/DiceMaiden#42]
Im GMing a game which sometimes requires 1D66 rolls. It means that you roll 2D6 and pick the tens from first dice and single digits from the second. The roll range is 11-66.

Currently I can just roll 2d6 and see the separate results but it would be cool to this supported.

**Comment by scottlafetra** [comment]
This can currently be done with `!roll 1d6 * 10 + 1d6`, but it might be useful to have an alias that expands `?d66` into `?d6 * 10 + ?d6`?

**Comment by Humblemonk** [comment]
Support for this type of rolls should now be live. It is documented under Alias on the readme. I am going to close this out. Can always re open if an issue crops up.
