### ISSUE TITLE
!roll 1d100 +50 t75 Incorrect Format

### ISSUE THREAD

**Issue by claycle** [Humblemonk/DiceMaiden#43]
Not quite sure why this wouldn't be legal according to the syntax guide:

!roll 1d100 +50 t75

gives "Incorrect format"

**Comment by Humblemonk** [comment]
Due to the way ruby gem works for the bots rolls, static modifiers(+ - * /) is expected at the end of the syntax. I will update the documentation. 

For example, that roll will work if you do !roll 1d100 t75 +50
