### ISSUE TITLE
Alias Support

### ISSUE THREAD

**Issue by scottlafetra** [Humblemonk/DiceMaiden#45]
This is probably something I'll work on next weekend, but I wanted to make an issue for it for tracking purposes. I think simply having an alias/regex map which was passed over the non-comment section of the input before the roll was made would be nice for more complex systems. For example:
Fate: `#dF` -> `#d6 t5 f2`
World of Darkness: `#WoD?` -> `#d10 t? f1`

**Comment by ahnion** [comment]
This would be very, very welcome. We just started running Changeling via Discord instead of IRL in these contagious times. Dice Maiden is really nice, but having a WoD macro like the one you describe would make things run a lot smoother.

**Comment by scottlafetra** [comment]
I'm deliberately leaving explosive results off for now until I can fix how explosions work. Say you roll `3WoD8` and get the results `[10, 10, 4, 3]`. Dice maiden currently only does one round of exploding so it's not immediately clear if another round of explosions need to be rolled. In future development (probably next week) I'll work on making dice maiden do indefinite explosions and format to look like: `[10, 4, 3] Explodes: [10] Explodes: [6]` or something. I'm still not sold on what the formatting should be. There's a couple of issues here that would be solved by such a feature.

**Comment by ahnion** [comment]
Makes sense. Thanks for working to fix the discrepancies and making the roller easier to use!

**Comment by Humblemonk** [comment]
Alias support should now be live!

**Comment by KaeAskavi** [comment]
Will exploding support be added to the WoD alias?  I see it is working for CoD.
