### ISSUE TITLE
Hero System 5e Damage/Effect Rolls

### ISSUE THREAD

**Issue by SmilingBanditUK** [Humblemonk/DiceMaiden#46]
Would you be able to add HS5e support?

It would include the following:

*Normal Damage:* (Suggested Syntax "!roll normal Xd6")
Roll X Number of d6.  The sum value is "Stun", "Body" is calculated on each dice : if it has a value of 1, +0 Body, a value of 2 - 5 is +1 Body, a value of 6 is +2 Body.
- !roll Normal 3d6, (6, 5, 1) would be 12 Stun (6+5+1), and 3 Body (+2, +1, +0) 
- !roll Normal 3d6, (6, 6, 6) would be 18 Stun (6+6+6), and 6 Body (+2, +2, +2)
- !roll Normal 3d6, (1, 2, 3) would be 6 Stun (6+6+6), and 2 Body (+0, +1, +1)
Output should be in the format of: '[name] has rolled Y Body and Z Stun'

*Killing Damage:* (Suggested Syntax "!roll killing Xd6 (smY)")
Roll X Number of d6.  The sum value is "Body", "Stun" is calculated by taking the Body Rolled and multiplying it by d6-1 (to a minimum of 1) (with a potential to manually add 1 or 2 Stun Multiplier by command).  
- !roll killing 3d6 (6, 5, 1) would be 12 Body, and it would then multiply that 12, by d6-1 (eg 3, for 36 Stun).
- !roll Killing 3d6 sm1 (6, 5, 1) would be 12 Body, and it would then multiply that 12, by d6 (eg 4, for 48 Stun).
- !roll Killing 3d6 sm2 (6, 5, 1) would be 12 Body, and it would then multiply that 12, by d6+1 (eg 5, for 60 Stun).
Output should be in the format of: '[name] has rolled Y Body and Z Stun'

*To Hit Roll:* (suggested Syntax: '!roll OCV X') 
This command would roll 3d6 and perform the following calculation:  (11+ provided OCV Value 'X') - 3d6 roll. 
- !roll OCV 7 would be 18 (11+7) - 3d6 (5, 4, 2 = 11) = 7
- !roll OCV 3 would be 14 (11+3) - 3d6 (1, 2, 1 = 4) = 10
Output should be in the format of '[name] has hit DCV 'Y'

**Comment by gypsyav** [comment]
I'll second this.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
I could _maaaybe_ do this? I think I'd make the syntax {!roll 3HSN}, {!roll 3HSK}, and {!roll 3HSH} respectively, with the 3 being the variable. Quicker to type, and making them all start with HS will make it less likely to conflict with possible future aliases for other systems. I'll also probably shorten the output somewhat, but I _might_ add the +0, 1, or 2 for the body to the tally of the Normal roll. If I'm still willing to mess with it after everything else.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Hmm. For this part:

`Killing Damage: (Suggested Syntax "!roll killing Xd6 (smY)")
Roll X Number of d6. The sum value is "Body", "Stun" is calculated by taking the Body Rolled and multiplying it by d6-1 (to a minimum of 1) (with a potential to manually add 1 or 2 Stun Multiplier by command)`

Is the 1 or 2 that's manually added to the multiplier applied before or after the "-1 (to a minimum of 1)"? As in, if that d6 roll was  a 1, and you were adding 1, would it be:
1-1=0 =>1, and then add the manual 1, for a total of 2, or
1-1+1=1, so it's not below the minimum, and that's your multiplier?

**Comment by gypsyav** [comment]
> Hmm. For this part:
> 
> `Killing Damage: (Suggested Syntax "!roll killing Xd6 (smY)") Roll X Number of d6. The sum value is "Body", "Stun" is calculated by taking the Body Rolled and multiplying it by d6-1 (to a minimum of 1) (with a potential to manually add 1 or 2 Stun Multiplier by command)`
> 
> Is the 1 or 2 that's manually added to the multiplier applied before or after the "-1 (to a minimum of 1)"? As in, if that d6 roll was a 1, and you were adding 1, would it be:
> 1-1=0 =>1, and then add the manual 1, for a total of 2, or
> 1-1+1=1, so it's not below the minimum, and that's your multiplier?

The way base killing damage works in the HERO system is you roll the number of dice of damage, say 3d6 and you roll an additional die and subtract 1 to determine the stun modifier. So you would get the following results from the stun modifier die:
roll                result
1                      1
2                      1
3                      2
4                      3
5                      4
6                      5

A +1 modifier just cancels out the -1 so the results would be:
1                      1
2                      2
3                      3
4                      4
5                      5
6                      6

Additional modifiers (you can purchase as many as the GM will allow) increase the stun multiplier.
               +2 example          +3 example            etc.
1                     2                            3                     "
2                     3                            4                     "
3                     4                            5                     "
4                     5                            6                     "
5                     6                            7                     "
6                     7                            8                     "

Hope that makes sense.

**Comment by SmilingBanditUK** [comment]
Yes, that logic tracks.

The only fly in the ointment seems to be the "partial dice" that you can have with Killing Dice.

The progression is: 1 Pip, ½d6, 1d6, 1d6+1, 1½d6, 2d6, 2d6+1, 2½d6, 3d6 and so on.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Yep, that answers my question! Thanks!

**Comment by ThatGuyWhatsMadeofCheese** [comment]
@SmilingBanditUK Ok, I really don't want to try to find a free pdf of the rulebook, so I don't know what you're talking about with the partial die. 

If I do what you asked in the original post, will players be able to do that part, (the partial die,) with a secondary roll fairly easily? Or is it something that you'd rather me delay finishing the first part to try to include that too?

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Alright, I've got the Normal and the to Hit parts done. The Killing part is going to be a pain, and I'll probably have to think it over for a day or a few before I come up with something that's clean enough it won't break right away. I also really might need to figure out how to host my own version so I can test it before I do a pull request, because this is bigger than the updates I've done before.

But progress, woo!

**Comment by gypsyav** [comment]
> Yes, that logic tracks.
> 
> The only fly in the ointment seems to be the "partial dice" that you can have with Killing Dice.
> 
> The progression is: 1 Pip, ½d6, 1d6, 1d6+1, 1½d6, 2d6, 2d6+1, 2½d6, 3d6 and so on.

Here are som examples of the above if it will help
`1 pip    =   1 point of damage
 1/2d6   =   1-3 points of damage
 1d6   =   1-6 points of damage
`

**Comment by ThatGuyWhatsMadeofCheese** [comment]
I got that much, but I don't know what it's added to, if it's before the multiplier or after, when it's decided to use it or not, that kind of thing.

Basically, I've never heard of Hero System outside of this issue, so I have no idea what it is ¯\_(ツ)_/¯

**Comment by SmilingBanditUK** [comment]
The partial dice are added before the multiplier for "Stun".  The total dice (including partials) are rolled to determine the Body Damage, and this total is multiplied by the "Stun Multiplier" (as per Gypsyavs tables) to determine the Stun Damage caused by the attack.

The modifiers to the Stun Multiplier are added to the d6-1 before multiplying by the Body rolled.

A paraphrased Example from the Rulebook:

"Armadillo slashes a policeman with his claws, which are considered a 2d6 Killing attack. The dice rolled are 3 and 4, for a total of 7 BODY. Armadillo then rolls 1d6 for his STUN Multiplier, rolling a 6. Since Armadillo has no modifiers to it, the STUN Multiplier is 1d6-1. He rolled a 6, so the STUN Multiplier is 6 - 1 = 5. The total STUN damage done is 7 x 5 = 35 STUN.  If he had had a +1 Stun Multiplier, he would have caused 7 x 6 = 42 STUN."

I hope this helps.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Ok, so I need to make sure I set up the killing attack alias in such a way that you can add either a +1 or a +1d3 to the end, that will get summed with the rest of the body, got it.

I'll see if I can make it '2HSK1', where the 2 is the number of d6, the 1 is the multiplier to be added to the d6-1, but it will default to 0 if none is given, and if you have partial die, you can just say '2HSK1 +1' or '2HSK1 +1d3' for a single pip or 1/2 d6, respectively.

Does that look like it'll cover it?

**Comment by SmilingBanditUK** [comment]
That looks ideal.  Thanks :)  And sorry for adding one of the more complicated Dice systems to your pile.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Eh, I'm doing it for fun. I just didn't try to tackle it until now because I'm still teaching myself ruby bit by bit, and when I first saw this a while back, I had no idea how to do it. But now I know how to do more stuff with regex and such, so I figured I'd give it a go.

But yeah, I did wonder why it was designed so... cumbersomely. Like, I've played games with much simpler basic combat that still dragged on far too much, and I tend to be the biggest math nerd at the table, so I'm just not sure who it's designed for. But to each their own I guess.

**Comment by SmilingBanditUK** [comment]
I think it's designed for people like me.  I am an Aspie (I have  Aspergers), and the way the system works, matches how I think about things in the real world.

It's a nightmare for most of my friends, but for me it just "clicks".

Oh, and I have improvised OCV, and ECV (Basically the same roll, but for Normal or Mental combat) and Normal Damage on my copy of your bot as follows:
Pattern: OCV Command: +11-(3d6) Regexp: False
Pattern: ECV Command: +11-(3d6) Regexp: False
Pattern: d6Normal Command: d6;$1c[>0]+$1c[=6]-$1c[=1] Regexp: False

:)

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Ah, that makes sense :) I'm that way with programming and algebra. Like, I think I was doing algebra-type thinking for basic arithmetic before learning algebra in the first place. But most the people I know hate it.

And just so I don't feel like I'm lying by omission; DiceMaiden is Humblemonk's project. I've just done a few small things in the last few months, since I got introduced to it by a discord group for a new game that's still in playtesting. I've mostly been using it as an excuse to learn github and ruby.

**Comment by gypsyav** [comment]
> I think it's designed for people like me. I am an Aspie (I have Aspergers), and the way the system works, matches how I think 

It just clicks for me too and somehow always made more sense to me than systems that use multiple different types of dice. Doing the math with d6s makes more sense to me than trying to remember whether to use a d8 or a d20 or was it a d6. I've played both and would rather do the math than find the right type of die.
