### ISSUE TITLE
Divert Output to other Channel

### ISSUE THREAD

**Issue by Thiatas** [Humblemonk/DiceMaiden#47]
Hi!

Love the dice roller, I have been looking for an alternative to online RPG platform rollers for some time and make heavy use of Discord.

I do have a request though, do you guys think it would be possible to program the bot to divert the output via a flag in the command to a different text channel on the server?

Thanks for your consideration guys!

**Comment by Humblemonk** [comment]
Might be a bit of time before this is supported. In the mean time, I suggest making a private chat channel in your Discord server to do GM rolls in :)

**Comment by Humblemonk** [comment]
Going to close this out as won't do. Thinking on it more, the work required here is nontrivial and would not provide a huge amount of value to the majority of users. I recommend utilizing private channels in discord or private message the bot rolls.
