### ISSUE TITLE
Modifier issues

### ISSUE THREAD

**Issue by KaitoXIII** [Humblemonk/DiceMaiden#49]

**Comment by KaitoXIII** [comment]
I've recently been having an issue with the static modifier function on the dice roller. When ever i ask it to multiply results together !roll xdx * xdx, it returns a value as if the the results were subtracted from each other instead

**Comment by scottlafetra** [comment]
Found the root of the problem, this should be solved shortly. Thanks for submitting the issue.

**Comment by KaitoXIII** [comment]
Thank you for your time and effort
