### ISSUE TITLE
Use @ or nicknames when addressing bot caller.

### ISSUE THREAD

**Issue by Subbarker** [Humblemonk/DiceMaiden#5]
My server makes heavy use of nicknames, so when a player calls the bot to roll for them, the message usually doesn't match what others see to be the user's name. I request that the bot @mentions the user so the right name is used or uses their nickname if they have one if you're worried about pinging people too much. 

example:
```
<nickname>
!roll 2d6
Dice Maiden
<username> Roll: [4, 4] Result: 8
```

**Comment by Humblemonk** [comment]
Yea I can look into supporting this.

**Comment by Humblemonk** [comment]
This is going live today. Let me know if you run into any issues.

**Comment by Subbarker** [comment]
I see no name at all now.

**Comment by Humblemonk** [comment]
Yep I see what I broke. Should be fixed today.

**Comment by Subbarker** [comment]
Working now.
