### ISSUE TITLE
Suddenly no longer possible to roll 1d2?

### ISSUE THREAD

**Issue by mpalmujoki** [Humblemonk/DiceMaiden#50]
We've been using Dice Maiden for quite some time.

Suddenly, I get this error:

![image](https://user-images.githubusercontent.com/8876090/78706531-ea47bc80-7917-11ea-8675-54a39cf204c4.png)

Guess it's a bug?

**Comment by Humblemonk** [comment]
Looking into that right now

**Comment by Humblemonk** [comment]
Found the bug. The fix is going out now. Will take ~20 minutes to propogate to all the shards.
