### ISSUE TITLE
REQUEST: Extended rolls to a target number

### ISSUE THREAD

**Issue by Auctorion** [Humblemonk/DiceMaiden#56]
In several systems there are mechanics for extended rolls to reach a certain target threshold. E.g. in WoD you have to get X number of successes over several rolls to determine how long something takes. It would be neat to have a function where Dice Maiden repeats a !roll command and provides a condensed summary of the roll results.

It currently leads to this:

![Screenshot 2020-04-16 at 16 28 37](https://user-images.githubusercontent.com/63723816/79475818-18a45680-8000-11ea-997f-4d6da975be0f.png)

**Comment by Humblemonk** [comment]
Could you utilize a roll set to get this done? For example:
`[11:26 AM] Humblemonk: !roll 10 14d10 t8 e10`
`[11:26 AM] BOT dice maiden - dogfood: Humblemonk Rolls:`
`[10, 9, 8, 8, 7, 7, 5, 5, 4, 4, 3, 2, 1, 1], [6] Result: 4`
`[10, 10, 9, 9, 8, 6, 5, 5, 5, 4, 3, 3, 2, 1], [9, 1] Result: 6`
`[10, 10, 9, 9, 9, 8, 7, 7, 6, 4, 4, 3, 2, 1], [10, 2] Result: 7`
`[9, 9, 9, 8, 8, 7, 5, 5, 5, 5, 4, 3, 2, 1] Result: 5`
`[10, 9, 9, 8, 7, 7, 7, 5, 3, 3, 2, 1, 1, 1], [1] Result: 4`
`[10, 9, 9, 8, 8, 8, 7, 7, 7, 6, 5, 1, 1, 1], [3] Result: 6`
`[10, 10, 9, 8, 8, 6, 6, 6, 4, 4, 3, 2, 2, 1], [10, 2] Result: 6`
`[10, 10, 10, 10, 9, 9, 8, 7, 7, 6, 5, 4, 3, 2], [9, 5, 3, 3] Result: 8`
`[10, 10, 9, 8, 8, 8, 7, 7, 6, 4, 4, 3, 1, 1], [7, 1] Result: 6`
`[10, 8, 8, 7, 6, 5, 4, 4, 3, 3, 2, 2, 2, 1], [1] Result: 3`

Adding the ability for dice maiden to remember a roll is a nontrivial task and something we do not plan on supporting anytime soon.

**Comment by Humblemonk** [comment]
Going to close this one out for now. I think roll sets should be able to do the job here.

**Comment by Auctorion** [comment]
Just to say, that _does_ work, it would just be neater to have it repeat the roll command only enough times to reach a threshold of successes that is >= a target number of successes.
