### ISSUE TITLE
REQUEST: Roll multiple dice of different sizes in one command

### ISSUE THREAD

**Issue by cambion70** [Humblemonk/DiceMaiden#60]
I'd like to be able to roll two dice in one !roll command. For example:
I want to roll 1d20 for my to-hit, then 1d8 for damage. If the hit is good, I already have the damage and I don't have to roll again. If the hit is a miss, just ignore the damage roll.

When I play in person, I always do this with physical dice. It's efficient.

I propose to do it as such:

!roll 1d20+1 & 1d8

This would simply give two results and display them. I don't think the & operator is used for anything else. And maybe it can support more than two... just use another & and append another dice expression.

I hope you will consider this for this project and thanks for reading!

**Comment by B-Rex** [comment]
@Humblemonk I'll pick this one up if it seems worthwhile to you?

**Comment by Humblemonk** [comment]
Yea go for it! I think it would a nice feature to support

**Comment by B-Rex** [comment]
Excellent, I'll get started on it.

**Comment by cambion70** [comment]
Any update on this?

**Comment by Humblemonk** [comment]
Still in the works. Wont be able to give an eta

**Comment by Humblemonk** [comment]
Getting this implemented now.  Going to be separating dice rolls with a forward slash. 

Example roll will be something like /roll 4d100 / 4d20 / 10d20 / 6d12
