### ISSUE TITLE
Multiply rolls together

### ISSUE THREAD

**Issue by crow8417** [Humblemonk/DiceMaiden#61]
I would like to be able to roll x amount of dice from a prior roll. For example, one of my bosses has an attack that does damage 1d8 * 1d2 times. So a max total hit of 16 and a minimum hit of 1. It would be cool if I could put in:
!roll 1d8 * 1d2; or
!roll 1d8 1d2; or
!roll (1d8) 1d2; to get that outcome instead of doing: 
!roll 1d8; holding this number and then rolling:
!roll 1d2; and multiplying the results together

Many thanks!

**Comment by Humblemonk** [comment]
This should now be supported. Example:
`[11:34 AM] Humblemonk: !roll 1d8 * 1d2`
`[11:34 AM] BOT dice maiden: Humblemonk Roll: [3][2] Result: 6`
