### ISSUE TITLE
Roll result exceeds character limit

### ISSUE THREAD

**Issue by ShadowGamer3** [Humblemonk/DiceMaiden#64]
Yeah, so i know not many people would actually need this, but the people in my discord server have been known to make completely unnecessary dice rolls for no apparent reason.  Therefore, in the interest of bug-fixing, here goes:

At the time of this posting, the bot supports up to 20 sets of dice being rolled, with a maximum die quantity of 500 dice-per-set, with a the biggest supported die being a d100. So you might be able to see where I'm going...

Discord also has a 2000 character limit, so... when someone goes and tries to !roll 20 500d100 (or some other similarly-but-excessively large roll, Dice Maiden throws up an error:

My attempt at !roll 20 500d100
"Unexpected exception thrown! (Message over the character limit (39528 > 2000)) 

Please drop us a message in the #support channel on the dice maiden server, or create an issue on Github."

So in these cases, a potential fix could be to break up the one too-big message into multiple, smaller ones.  It could work (and look fine) considering discord doesn't break up your sequential messages as long as they're pretty close in time and no-one else sends one in the middle. that aside though you can still get the entire message out (just in smaller chunks) without violating the character limit.

That, or just display the total of those rolls in such cases, and not the dice behind them (though personally I like seeing the numbers behind the rolls)

**Comment by Humblemonk** [comment]
So due to the way discord rate limits how many messages you can send at any given time, breaking the roll up into multiple messages may not be a viable option here. I think that leaves two options:

1. Deny the roll with a clear error that its too large 
2. Simplify the output with a reason why

**Comment by ShadowGamer3** [comment]
Personally, I'd be fine with either of those.  Error from atoo large a message gets it across fine, and you can just make fewer rolls, wheras simplifying the output would at least give you the number.

**Comment by Humblemonk** [comment]
Fix for this going out today. Going the route of simplifying the roll when character limit is exceeded.
