### ISSUE TITLE
Dice Maiden was spamming outside of its channel

### ISSUE THREAD

**Issue by keserdraak** [Humblemonk/DiceMaiden#67]
I had to mute the Dice Maiden bot, it was spamming error messages to two random Discord text channels, seemingly for no reason. It's normally confined to a specific text channel for dice rolling.

**Comment by Humblemonk** [comment]
Yea sorry about that, a recent merge caused a massive bug which made commands start spamming across multiple channels.

I am trying to fix the bug asap. Bot should be coming back up within the hour. I will respond here once its back up.

**Comment by Humblemonk** [comment]
Bot is back up! Please update this issue if you notice any immediate issues. Thanks and sorry for the recent issues :)

**Comment by Humblemonk** [comment]
Going to leave this open for a couple days before closing it out
