### ISSUE TITLE
Strange text when rolling

### ISSUE THREAD

**Issue by kaloisgone** [Humblemonk/DiceMaiden#68]
Trying to play a game right now and a few of our more complicated rolls has given us strange text commands such as, 
"Dog Hater Roll: `` Result:"
"Big head Big head Big head Roll: `` Result:"
"Moonlight Roll: `` Result:"

not sure why its doing it. it doesnt seem to be every roll, but it happens often

**Comment by Humblemonk** [comment]
Thanks for the report, we are looking into it now. Looks to be a race condition with the recent commits. Should have a workaround out tonight. Will update this thread once its out

**Comment by Humblemonk** [comment]
Pushing out a workaround for now to all the shards. Going to leave this open for a few days. Post here if you notice any issues. Thanks!
