### ISSUE TITLE
Bot was offline for a few hours and came back weird

### ISSUE THREAD

**Issue by pvt900** [Humblemonk/DiceMaiden#69]
So the Dice Maiden bot was offline for about an hour tonight and I resorted to using alternative bots for the duration however I discovered it came back and noticed while it worked with the !roll command it is now also reading commands with 1 which I have assigned to another bot that does similar functions and now if someone uses that bot such ass (1roll 2d10) it rolls 2d10 on both bots. I did not have Dice Maiden to roll on any character other than a !.

**Comment by pvt900** [comment]
![image](https://user-images.githubusercontent.com/53491379/81781750-4032f580-94be-11ea-9032-100a857060a7.png)

**Comment by Humblemonk** [comment]
Thanks for posting this bug! I was getting reports from other users as well. I am pushing out a fix right now. The bot should start to properly check the servers chosen prefix again.

**Comment by Humblemonk** [comment]
Fix is out now. Going to leave this issue open for a couple days. Please comment if you notice any issues!
