### ISSUE TITLE
!roll 1d1e1

### ISSUE THREAD

**Issue by jangodracor** [Humblemonk/DiceMaiden#7]
Completely broke the bot. I understand that this makes an infinite loop. I did it for the meme. But even after kicking and re adding dice maiden to my server we can't use any dice maiden features

**Comment by Humblemonk** [comment]
Hah! Thanks for letting me know. I just denied rolling any device value less than 2 and restarted the bot. Let me know if you run into any more issues.

**Comment by jangodracor** [comment]
Aw man I liked my roll 1d1 "haha nat 1" joke, bummer, but the bot is
definitely working again thanks!
