### ISSUE TITLE
new feature request- see request and name in roll

### ISSUE THREAD

**Issue by jrwizzard** [Humblemonk/DiceMaiden#70]
Would like to be able to see  what the roll request was in the results.

!roll 1d20 +2 !Dex save

should result in:

personsname Roll: [2] Result: 4 Reason: Dex save [1d20 +2]

Reason: would like to be able to see all of it together in one place, so if I know the person has more/less dex bonus, i can mention it and make adjustments. I know it is a bit nitpicky, but it would be more convenient for me. maybe add it as a server option or something.

Thanks, great bot

**Comment by Humblemonk** [comment]
This is now supported! 

You can set the bot to display the actual roll executed as part of the bot response with this server-wide option. This is off by default.

!dm request show : Show the roll requests in the output.

!dm request hide : Hide the roll requests in the output.

**Comment by Humblemonk** [comment]
Quick update: found an issue with the current implementation. Working on getting it fixed. Will update this thread once that is done.

**Comment by Humblemonk** [comment]
This is good to go now :)
