### ISSUE TITLE
Alias Request: Call of Cthulhu Bonus die/penalty die

### ISSUE THREAD

**Issue by pooserville** [Humblemonk/DiceMaiden#71]
coc+d100 -> !roll ((2d10kl1 -1) *10) + 1d10! Bonus die (roll twice for 10s digit + keep lowest)
coc-d100 -> !roll ((2d10k1 -1) *10) + 1d10! Penalty die (roll twice for 10s digit + keep highest)

Call of Cthulhu is a roll-under system which is why the keeping the lower die is a bonus.

**Comment by Humblemonk** [comment]
Support for this was just added. Documentation for the new aliases:

+d% -> ((2d10kl1-1) *10) + 1d10 Advantage roll for a percentile dice in a roll-under system. Rolls two tens and keeps the lowest.

-d% -> ((2d10k1-1) *10) + 1d10 Disadvantage roll for a percentile dice in a roll-under system. Rolls two tens and keeps the highest.
