### ISSUE TITLE
!roll 1d6 e4 r3

### ISSUE THREAD

**Issue by Xhosant** [Humblemonk/DiceMaiden#75]
As you may expect, the above command will lock the dicebot for quite some time. I did notice that the likes of e1 or r6 are rejected, so I figured you'd care to know that combining the two can bypass the filtering!

**Comment by Xhosant** [comment]
Off the top of my head, comparing the parameters for e and r to make sure they're not e<=r+1 can filter these behaviors!

**Comment by Humblemonk** [comment]
Nice catch! Yea a few roll types can break the bot. Instead of just fixing each one that comes along, I will implement a timer of sorts and break out of the roll if its taking too long as to not impact the queue.

**Comment by Humblemonk** [comment]
This should now be resolved

**Comment by Humblemonk** [comment]
Going to close this one out by friday
