### ISSUE TITLE
Keeps going offline

### ISSUE THREAD

**Issue by Dazz1286** [Humblemonk/DiceMaiden#8]
The Dice Maiden bot often appears offline and when this occurs the commands no longer work.

**Comment by Humblemonk** [comment]
Thanks for letting me know. I have been running into issues recently with where the bot is hosted as well as the bot scaling. The ruby discord API library is designed more for convenience than scalability. Potential plans are to rewrite the bot in a different language.

Anyways, bot is being moved and should be back up shortly
