### ISSUE TITLE
Crash with !roll d8e8r1r2r3r4r5r6r7

### ISSUE THREAD

**Issue by JustGamingLTD** [Humblemonk/DiceMaiden#83]
**Describe the bug**
When you give the following command "!roll d8e8r1r2r3r4r5r6r7" the bot crashes for a few minutes.

**To Reproduce**
Go to a server where dice maiden is in.
Send her the command "!roll d8e8r1r2r3r4r5r6r7"

**Expected behavior**
There is no expected behavior, except maybe returning infinity or an error.

**Comment by Humblemonk** [comment]
This should now be resolved

**Comment by Humblemonk** [comment]
Going to close this one out by friday
