### ISSUE TITLE
Unsort not supported with indefinite explosions

### ISSUE THREAD

**Issue by Humblemonk** [Humblemonk/DiceMaiden#88]
**Describe the bug**
Currently,  we do not unsort the tally when doing rolls with the explosion flags

**To Reproduce**
 !roll ul 10d10 e10
or
!roll ul 10d10 ie10

**Expected behavior**
We should unsort the tallies

**Comment by ThatGuyWhatsMadeofCheese** [comment]
For some reason, if you try to reproduce with a custom prefix, (I used !r), it unsorts, but doesn't explode.

**To Reproduce**
!dm prefix r
!r ul 10d10 ie10

**Comment by Humblemonk** [comment]
This should actually be exploding correctly now. The unsort command will be pooling all dice rolled including exploded dice.
