### ISSUE TITLE
Allow fixed numbers for starting values and math functions

### ISSUE THREAD

**Issue by gamerzen** [Humblemonk/DiceMaiden#9]
Basically, I'd love it if you could use the dice bot to perform functions like:
!roll 9-2d6

Currently, starting with a number means the dice bot does not give a result.

**Comment by Humblemonk** [comment]
Due to how the ruby gem works that the bot relies on for dice rolls, this probably won't be done for some time.

**Comment by Humblemonk** [comment]
This is now supported!
