### ISSUE TITLE
rolls do not succeed if the comment contains the word "kidneys"

### ISSUE THREAD

**Issue by thatandromeda** [Humblemonk/DiceMaiden#90]
**Describe the bug**
In a gaming session, we found that the following command did not result in dice being rolled:
`!roll 2d10+3 !I like my kidneys`

However, `!roll 2d10+3 !I like my liver` worked fine.

Other attempts with the word 'kidneys' also failed. (e,g, `!roll 1d6 !kidneys`, `!roll 2d10+2 !Spray their kidneys!`)

**To Reproduce**
Go to a Discord room with DiceMaiden. Type one of the above commands. Nothing happens.

**Expected behavior**
I expect to see the results of the die roll.

**Additional context**
After some rephrasing, the paladin in question protected his internal organs with a full success.

**Comment by Chuckaluphagus** [comment]
Can confirm.

**Comment by Humblemonk** [comment]
Ok this is a pretty funny bug. Thanks for letting us know! We will look into it

**Comment by Humblemonk** [comment]
Already found the issue. Issue will be resolved tomorrow.

**Comment by thatandromeda** [comment]
Amazing, thanks!

**Comment by gatherer818** [comment]
I really want to know what was causing this problem.  If you remember, can you say?

**Comment by ShadowGamer3** [comment]
Holy crap! What a bug... now I’m curious!  What was causing it?

**Comment by Humblemonk** [comment]
The wrath and glory game system check for "difficulty number" was incorrectly checking comments. Any comment with the characters "dn" in it were causing the bot to error out.

**Comment by gatherer818** [comment]
Ah, the "magic combination of letters", that makes sense.  Thanks for taking the time to satisfy our idle curiosity <3
