### ISSUE TITLE
Request: alias for CoD (wod 5th) dice roll

### ISSUE THREAD

**Issue by razhar1980** [Humblemonk/DiceMaiden#93]
**Is your feature request related to a problem? Please describe.**
Just wanted to add a alias to the Chronicles of Darkness dice rolls. 
So it will be shorter and easier to do.

**Describe the solution you'd like**
An alias like the used to "wod" just like "cod"

**Describe alternatives you've considered**
What I use to roll the dice in the rules of CoD is 
!roll #d10 t8 ie10 (# is the number of dices, everything above 8 is a sucess. every 10 is explosion) 

**Additional context**
Since theres no need of changing the difficulty (8, 9 and 10 are sucess) the alias could be just "cod"
So a roll will be called like: !roll 6cod

**Comment by Auctorion** [comment]
Doesn't include possibility for explosion threshold changing, i.e. 9-again and 8-again. I'd suggest a number on the end to indicate, e.g. !roll 6cod9 for 9-again.

**Comment by razhar1980** [comment]
I see your point, but by the rules of CoD, only, and always the 10 have explosion, so the sufix it is not needed.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
[/\b\d+CoD\b/i, "CoD", /\b(\d+)CoD\b/i, "\\1d10 ie10 t8"], # Chronicles of Darkness

**Comment by Humblemonk** [comment]
Going to try and get this alias merged today based on ThatGuyWhatsMadeofCheese's syntax

**Comment by Humblemonk** [comment]
This is being deployed now.

**Comment by Auctorion** [comment]
> I see your point, but by the rules of CoD, only, and always the 10 have explosion, so the sufix it is not needed.

That's literally not true though. 9-again and 8-again are a **_core_** part of the rules and change the threshold upon which the dice explode. 10's always explode, yes. But for some characters in some circumstances, 9s and 8s can explode. For example, Demons using Merciless Gunman "gain the 8-again quality for a Firearms attack" when not using down and dirty combat, so they'll have dice exploding on 8s, 9s, and 10s.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
It should be noted that the last instance of a flag in the command overrides all previous ones. So, if you type `!roll cod7 ie8`, what will actually happen is `!roll 7d10 ie8 t8`

It sounds to me like it's rare enough to not add another digit you always need to type to the alias, but maybe add that explanation to the ReadMe?
