### ISSUE TITLE
Add argument to show Reroll attempts and/or Reroll count

### ISSUE THREAD

**Issue by ShadowGamer3** [Humblemonk/DiceMaiden#94]
As it stands at the time of post, the ir arguments indefinitely reroll until the result is higher than the given number.

This is fine, but it would be nice, (and possibly useful) to be able to add an argument to show the failed attempts, and/or the number of failed attempts. 

This can also be applied to the normal rerolls too, so if it does need to be rerolled, then it will tell you. 

Candidate syntax:

!roll 5d6 ir1 s  (Result: 2, 3, 5, 5, 6  ;  3 Rerolls  ; total 21)

!roll 7d6 ir1 s r2 s d1 (Original Result: 2, 3, 4, 4, 5, 6, 6  ;  4 Rerolls, Reroll 2: 4  ;  Total: 29)

!roll 3d4 r1 s (Original Result: 1, 3, 4  ;  Reroll 1: 2  ;  Total: 9)

Candidate Arguments: 

s, à

If nothing else, this could help add authenticity, but I’m sure there are uses for it out there. Personally I think it makes it feel more like real dice.

**Comment by Humblemonk** [comment]
I think this is a good idea to show how many rerolls happened. I dont think I will want this to be another flag further complicating rolls but rather bake it into the existing rerolls. Something like showing the total reroll count after the tally.

**Comment by Humblemonk** [comment]
Support for showing total rerolls for a specific roll is going out today. It will look like the following example:

[1:15 AM] Humblemonk: !roll 4d10 r9
[1:15 AM] BOT dice maiden Humblemonk Roll: [10, 9, 5, 1] Rerolls: 3 Result: 25
