### ISSUE TITLE
Drop/keep order isn't working like described

### ISSUE THREAD

**Issue by gatherer818** [Humblemonk/DiceMaiden#95]
Attempting to "roll 3, keep middle" using d1 kl1 (drop lowest, keep lowest remaining) is keeping the lowest roll.

**To Reproduce**
!roll 3d20 d1 kl1

**Expected behavior**
Expected to keep middle roll;  example set [20, 10, 1] should drop the 1 then keep the 10.

**Screenshots**
![image](https://user-images.githubusercontent.com/68674940/88248656-ec881980-cc6f-11ea-8ad3-e110467dff4c.png)

**Comment by Humblemonk** [comment]
Thanks for the bug report! An update is going out for the ruby gem dicebag, commit found [here](https://github.com/Humblemonk/Dice-Bag/commit/97f071da6c5981d6af5bd2aa26280256d46d95e0). You should see the change go live in the next 20 minutes
