### ISSUE TITLE
Request: Pre-Written Alias

### ISSUE THREAD

**Issue by ThatGuyWhatsMadeofCheese** [Humblemonk/DiceMaiden#97]
I'm requesting an alias for Sunsails: New Millennium, which I'm in a play-testing group for. Almost all rolls will follow the same format, so a simple [snm3 -> 3d6 ie6 t4] will save a lot of typing. 

I know that wouldn't be high on the priority list, so I took a few minutes to learn the relevant parts of regex and wrote the needed line of code:

` [/\bSNM\d+\b/i, "SNM", /\bSNM(\d+)\b/i, "\\1d6 ie6 t4"], # Sunsails: New Milennium; Fourth Edition`

I don't have an environment to test it in, but I'm reasonably sure it will work.

Thank you in advance, even if you don't add it, as Dice Maiden as-is is already quite helpful :)

**Comment by Humblemonk** [comment]
Thanks for submitting a PR! I will try and take a look at this Friday and see if we can get it merged.

**Comment by MarshallOliver** [comment]
No problem.  I also play this game, so it'll be helpful to at least 2 people.  ;p
